"""Code generator — takes a Recommendation + Brief and produces frontend code.

This is intentionally a thin layer. The Recommendation has already done the
hard reasoning (industry → style → palette → type → motion → components +
guardrails). The generator's job is to:

1. Emit a design-tokens file (CSS variables or TS export) reflecting the
   recommendation.
2. Emit per-component skeletons for the picked components, in the requested
   stack.
3. Embed the guardrail comment block at the top of every generated file so
   anyone editing later sees the rules.

For v2.0.0-alpha, the generator emits stack-agnostic CSS tokens + a manifest
JSON the calling command (in Claude Code) can use to drive its own code-gen.
Stack-specific emitters land in v2.0.0-beta.

Public surface
--------------
``generate(recommendation, brief, out_dir) -> GeneratedBundle``
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Any, Dict, List, Optional

from engine.recommender.core import Brief, Recommendation


@dataclass
class GeneratedBundle:
    out_dir: str
    files_written: List[str] = field(default_factory=list)
    summary: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


def _emit_tokens_css(rec: Recommendation) -> str:
    palette = (rec.palette or {}).get("colors", {})
    type_pair = rec.type_pair or {}
    lines = [
        "/* ux-skill v2 — generated design tokens */",
        "/* DO NOT EDIT this file directly. Re-run `ux generate` to refresh. */",
        ":root {",
    ]
    for key, value in palette.items():
        if isinstance(value, str):
            lines.append(f"  --color-{key.replace('_', '-')}: {value};")

    display = type_pair.get("display", {}).get("family")
    body = type_pair.get("body", {}).get("family")
    mono = type_pair.get("mono", {}).get("family")
    if display:
        lines.append(f"  --font-display: \"{display}\", serif;")
    if body:
        lines.append(f"  --font-body: \"{body}\", system-ui, sans-serif;")
    if mono:
        lines.append(f"  --font-mono: \"{mono}\", ui-monospace, monospace;")

    lines.append("}")
    return "\n".join(lines) + "\n"


def _emit_guardrail_header(rec: Recommendation) -> str:
    header = ["/* ux-skill v2 — generated. Active guardrails:"]
    for g in rec.guardrails[:10]:
        header.append(f" * - [{g.get('severity')}] {g.get('name')}")
    if len(rec.guardrails) > 10:
        header.append(f" * ...and {len(rec.guardrails) - 10} more in data/anti-patterns.json")
    header.append(" */")
    return "\n".join(header) + "\n\n"


def _emit_manifest(rec: Recommendation, brief: Brief) -> str:
    payload: Dict[str, Any] = {
        "brief": asdict(brief),
        "picks": {
            "style": (rec.style or {}).get("id"),
            "palette": (rec.palette or {}).get("id"),
            "type_pair": (rec.type_pair or {}).get("id"),
            "motion_presets": [m.get("id") for m in rec.motion],
            "components": [c.get("id") for c in rec.components],
            "brand_exemplars": [b.get("id") for b in rec.brand_exemplars],
        },
        "guardrails_active": len(rec.guardrails),
        "rationale": rec.rationale,
    }
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def generate(
    recommendation: Recommendation,
    brief: Optional[Brief] = None,
    out_dir: str = "./.ux/generated",
) -> GeneratedBundle:
    """Write the generated tokens + manifest to ``out_dir``.

    Returns a ``GeneratedBundle`` describing what landed. Idempotent — safe
    to re-run; will overwrite files in ``out_dir``.
    """
    brief = brief or Brief()
    target = Path(out_dir)
    target.mkdir(parents=True, exist_ok=True)

    tokens_path = target / "tokens.css"
    tokens_path.write_text(
        _emit_guardrail_header(recommendation) + _emit_tokens_css(recommendation),
        encoding="utf-8",
    )

    manifest_path = target / "manifest.json"
    manifest_path.write_text(_emit_manifest(recommendation, brief), encoding="utf-8")

    return GeneratedBundle(
        out_dir=str(target),
        files_written=[str(tokens_path), str(manifest_path)],
        summary={
            "style": (recommendation.style or {}).get("id"),
            "palette": (recommendation.palette or {}).get("id"),
            "type_pair": (recommendation.type_pair or {}).get("id"),
            "guardrails": len(recommendation.guardrails),
        },
    )
