"""Find an existing design system in a project and read what it declares.

Deterministic and offline. Reads files only; never runs the project's
build script and never writes.
"""
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple

# The frontmatter key and value ux-skill writes into a MASTER.md it owns.
OWNER_KEY = "generated_by"
OWNER_VALUE = "ux-skill"
# The phrase `ux design-md` writes into every DESIGN.md it creates.
DESIGN_MD_MARKER = "Generated by ux-skill"
# The exact first heading MASTER.md had before the owner key existed.
_LEGACY_MASTER_HEADING = "# Design system \u2014 MASTER"
_LEGACY_MASTER_KEYS = {"project", "page", "last_updated", "ux_skill_version"}

# Folders a design system conventionally lives in, relative to the root.
_SYSTEM_DIRS = (
    "design-system", "design-tokens", "tokens", "packages/tokens", "packages/design-tokens",
    "packages/foundation", "packages/foundations", "packages/design-system",
    "src/tokens", "src/design-system", "src/theme", "theme", "styles", "src/styles", "src/css",
    "app/styles", "css", "assets/css", "assets/styles", "static/css", "public/css",
)
# A folder under packages/ whose name holds one of these words is a system folder too.
_PACKAGE_WORDS = ("token", "design", "foundation", "theme", "style")
_SKIP_DIRS = {"node_modules", ".git", ".ux", ".venv", "venv", "__pycache__", ".next",
              ".claude", ".cache", "vendor"}
_MAX_DEPTH = 4
_MAX_FILES = 4000

_TOKEN_FILE_RE = re.compile(r"^(?:design-)?tokens(?:\.[\w-]+)?\.json$|\.tokens\.json$", re.I)
_BUILD_SCRIPT_RE = re.compile(
    r"^(?:build(?:-tokens)?|resolve[\w-]*|resolver|style-dictionary\.config|sd\.config|"
    r"tokens\.config)\.(?:mjs|cjs|js|ts|py)$", re.I)
_FOUNDATION_CSS_RE = re.compile(r"(?:^|[-_.])(?:foundations?|tokens|variables|theme)\.css$", re.I)
_CUSTOM_PROP_RE = re.compile(r"(--[A-Za-z0-9_-]+)\s*:\s*([^;{}]+)")
_VAR_RE = re.compile(r"var\(\s*(--[A-Za-z0-9_-]+)\s*(?:,\s*([^()]*(?:\([^()]*\)[^()]*)*))?\)")
_HTML_LANG_RE = re.compile(r"<html\b[^>]*\blang\s*=\s*['\"]([A-Za-z]{2,3})(?:-[A-Za-z0-9-]+)?['\"]", re.I)
_HTML_RTL_RE = re.compile(r"<html\b[^>]*\bdir\s*=\s*['\"]rtl['\"]", re.I)
_HEX_RE = re.compile(r"^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$")
_RGB_RE = re.compile(r"^rgba?\(\s*(\d{1,3})[\s,]+(\d{1,3})[\s,]+(\d{1,3})\s*(?:[,/][^)]*)?\)$", re.I)

_PRIMARY_WORDS = {"primary", "brand"}
_NOT_PRIMARY = {
    "hover", "pressed", "active", "focus", "disabled", "on", "subtle", "muted", "soft",
    "container", "text", "fg", "foreground", "ink", "border", "outline", "inverse", "weak",
    "strong", "dark", "tint", "shade", "alpha", "variant", "secondary", "tertiary", "bg",
    "background", "surface", "light", "faint", "ring", "shadow",
}
_TEXT_WORDS = {"text", "ink", "fg", "foreground", "content"}
_NOT_TEXT = {
    "on", "inverse", "disabled", "link", "accent", "muted", "secondary", "tertiary", "subtle",
    "placeholder", "hover", "brand", "primary-on", "danger", "error", "success", "warning",
    "info", "dark", "weak", "faint", "selection",
}
_TEXT_BEST = {"primary", "default", "base", "strong", "body", "main"}
_DISPLAY_WORDS = {"display", "heading", "headline", "head", "title"}
_BODY_WORDS = {"body", "base", "text", "sans", "default", "ui", "copy"}


# ------------------------------------------------------------------ helpers


def normalize_hex(value: Any) -> str:
    """A color as #RRGGBB upper case, or "" when it is not a plain color."""
    if isinstance(value, dict):
        hx = value.get("hex")
        if isinstance(hx, str):
            return normalize_hex(hx)
        comps = value.get("components")
        if isinstance(comps, list) and len(comps) >= 3:
            try:
                rgb = [max(0, min(255, int(round(float(c) * 255)))) for c in comps[:3]]
            except (TypeError, ValueError):
                return ""
            return "#%02X%02X%02X" % tuple(rgb)
        return ""
    if not isinstance(value, str):
        return ""
    s = value.strip()
    m = _RGB_RE.match(s)
    if m:
        rgb = [max(0, min(255, int(g))) for g in m.groups()]
        return "#%02X%02X%02X" % tuple(rgb)
    if not _HEX_RE.match(s):
        return ""
    h = s[1:]
    if len(h) in (3, 4):
        h = "".join(c * 2 for c in h[:3])
    return "#" + h[:6].upper()


def _segments(path: str) -> List[str]:
    return [s for s in re.split(r"[.\-_/\s]+", path.lower()) if s]


def _read_text(path: Path, limit: int = 2_000_000) -> str:
    try:
        data = path.read_bytes()[:limit]
    except OSError:
        return ""
    return data.decode("utf-8", errors="ignore")


def _parse_frontmatter(text: str) -> Tuple[Dict[str, str], str]:
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}, text
    meta: Dict[str, str] = {}
    for idx, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            return meta, "\n".join(lines[idx + 1:])
        m = re.match(r"^([A-Za-z0-9_]+)\s*:\s*(.*)$", line)
        if m:
            meta[m.group(1)] = m.group(2).strip().strip('"').strip("'")
    return {}, text


def is_ux_skill_file(path: Any) -> bool:
    """True when ux-skill wrote this file: a MASTER.md or page file carrying
    the owner key (or the exact shape ux-skill wrote before the key
    existed), or a DESIGN.md carrying the design-md marker. A file that
    does not exist is not owned by anyone."""
    p = Path(path)
    if not p.is_file():
        return False
    text = _read_text(p)
    meta, body = _parse_frontmatter(text)
    if meta.get(OWNER_KEY, "").startswith(OWNER_VALUE):
        return True
    if p.name.upper() == "DESIGN.MD":
        return DESIGN_MD_MARKER in text
    first = next((ln for ln in body.splitlines() if ln.strip()), "")
    if meta and set(meta) <= _LEGACY_MASTER_KEYS and (
            first.strip() == _LEGACY_MASTER_HEADING or first.startswith("# Page \u2014 ")):
        return True
    return False


# ------------------------------------------------------------------ DTCG


def _is_token(node: Any) -> bool:
    if not isinstance(node, dict):
        return False
    if "$value" in node:
        return True
    return "value" in node and not isinstance(node.get("value"), dict) and (
        "type" in node or set(node) <= {"value", "type", "description", "comment"})


def flatten_dtcg(doc: Any) -> Dict[str, Dict[str, Any]]:
    """Every token in a DTCG (or Tokens Studio) document as
    ``{dotted.path: {"type": ..., "value": resolved}}``. References such as
    ``{color.blue.500}`` are resolved; a reference that cannot be resolved
    keeps its text."""
    raw: Dict[str, Dict[str, Any]] = {}

    def walk(node: Any, path: List[str], inherited: Optional[str]) -> None:
        if not isinstance(node, dict):
            return
        typ = node.get("$type") or node.get("type") if _is_token(node) else node.get("$type")
        typ = typ or inherited
        if _is_token(node):
            value = node.get("$value", node.get("value"))
            raw[".".join(path)] = {"type": typ or "", "value": value}
            return
        for key, child in node.items():
            if key.startswith("$"):
                continue
            walk(child, path + [key], typ)

    walk(doc, [], None)

    def resolve(value: Any, depth: int = 0) -> Any:
        if depth > 24:
            return value
        if isinstance(value, str):
            m = re.fullmatch(r"\{([^{}]+)\}", value.strip())
            if m and m.group(1) in raw:
                return resolve(raw[m.group(1)]["value"], depth + 1)
        return value

    out: Dict[str, Dict[str, Any]] = {}
    for key, tok in raw.items():
        value = resolve(tok["value"])
        typ = tok["type"]
        if not typ and normalize_hex(value):
            typ = "color"
        out[key] = {"type": typ, "value": value}
    return out


def _rank_primary(names: Iterable[Tuple[str, str]]) -> Tuple[str, str]:
    best: Optional[Tuple[Tuple[int, int, int], str, str]] = None
    for order, (name, hx) in enumerate(names):
        segs = _segments(name)
        if not hx or not segs or segs[-1].isdigit():
            continue
        words = set(segs)
        hits = words & _PRIMARY_WORDS
        if not hits or words & _NOT_PRIMARY:
            continue
        score = (-len(hits), len(segs), order)
        if best is None or score < best[0]:
            best = (score, name, hx)
    return (best[1], best[2]) if best else ("", "")


def _rank_text(names: Iterable[Tuple[str, str]]) -> Tuple[str, str]:
    best: Optional[Tuple[Tuple[int, int, int], str, str]] = None
    for order, (name, hx) in enumerate(names):
        segs = _segments(name)
        if not hx or not segs or segs[-1].isdigit():
            continue
        words = set(segs)
        if not words & _TEXT_WORDS or words & _NOT_TEXT:
            continue
        score = (0 if words & _TEXT_BEST or segs[-1] in _TEXT_WORDS else 1, len(segs), order)
        if best is None or score < best[0]:
            best = (score, name, hx)
    return (best[1], best[2]) if best else ("", "")


def _first_family(value: Any) -> str:
    if isinstance(value, list):
        value = value[0] if value else ""
    if not isinstance(value, str):
        return ""
    return value.split(",")[0].strip().strip('"').strip("'")


def _fonts_from(names: Iterable[Tuple[str, str]]) -> Dict[str, str]:
    display = body = ""
    for name, family in names:
        if not family:
            continue
        words = set(_segments(name))
        if not display and words & _DISPLAY_WORDS:
            display = family
        elif not body and (words & _BODY_WORDS or not words & _DISPLAY_WORDS):
            body = family
    fonts: Dict[str, str] = {}
    if display or body:
        fonts = {"display": display or body, "body": body or display}
    return fonts


# ------------------------------------------------------------------ CSS


def css_custom_properties(text: str) -> Dict[str, str]:
    """Every ``--name: value`` declaration in CSS text, first one wins."""
    text = re.sub(r"/\*.*?\*/", "", text or "", flags=re.S)
    props: Dict[str, str] = {}
    for m in _CUSTOM_PROP_RE.finditer(text):
        props.setdefault(m.group(1), m.group(2).strip())
    return props


def resolve_css_var(value: str, props: Dict[str, str], depth: int = 0) -> str:
    """Follow ``var(--x)`` chains to the final value (fallbacks honored)."""
    if depth > 24 or not isinstance(value, str):
        return value or ""
    m = _VAR_RE.fullmatch(value.strip())
    if not m:
        return value.strip()
    name, fallback = m.group(1), m.group(2)
    if name in props:
        return resolve_css_var(props[name], props, depth + 1)
    return resolve_css_var(fallback, props, depth + 1) if fallback else ""


# ------------------------------------------------------------------ walk


def _walk(base: Path, depth: int, seen: set, out: List[Path]) -> None:
    if depth > _MAX_DEPTH or len(out) >= _MAX_FILES:
        return
    try:
        entries = sorted(base.iterdir())
    except OSError:
        return
    for entry in entries:
        if entry.name in _SKIP_DIRS or entry.is_symlink():
            continue
        if entry.is_dir():
            _walk(entry, depth + 1, seen, out)
        elif entry.is_file():
            key = str(entry.resolve())
            if key not in seen:
                seen.add(key)
                out.append(entry)


def _looks_dtcg(path: Path) -> Optional[Any]:
    text = _read_text(path)
    if '"$value"' not in text and '"value"' not in text:
        return None
    try:
        doc = json.loads(text)
    except ValueError:
        return None
    return doc if isinstance(doc, dict) and flatten_dtcg(doc) else None


def _package_token_scripts(root: Path) -> List[str]:
    pkg = root / "package.json"
    if not pkg.is_file():
        return []
    try:
        scripts = (json.loads(_read_text(pkg)) or {}).get("scripts") or {}
    except (ValueError, AttributeError):
        return []
    return sorted(k for k in scripts if "token" in k.lower())


def _html_languages(files: List[Path]) -> List[str]:
    counts: Dict[str, List[int]] = {}
    for order, path in enumerate(files):
        if path.suffix.lower() not in (".html", ".htm"):
            continue
        head = _read_text(path, 20_000)
        m = _HTML_LANG_RE.search(head)
        if not m:
            continue
        lang = m.group(1).lower()
        rec = counts.setdefault(lang, [0, 0, order])
        rec[0] += 1
        if _HTML_RTL_RE.search(head):
            rec[1] += 1
    return [lang for lang, _ in sorted(counts.items(),
                                       key=lambda kv: (-kv[1][0], -kv[1][1], kv[1][2]))]


def detect_existing_system(root: Any = ".") -> Dict[str, Any]:
    """Find an existing design system under ``root`` and read what it declares.

    Returns ``{"found", "root", "sources", "declared"}``. ``sources`` lists
    each file or folder found as ``{"kind", "path"}`` with the path relative
    to ``root``; kinds are ``tokens`` (a DTCG or tokens JSON file),
    ``build-script``, ``css-foundation``, ``master-md``, ``design-md`` and
    ``system-folder``. ``declared`` holds ``primary`` and ``primary_token``,
    ``text`` and ``text_token``, ``fonts`` ({display, body}), ``colors``
    (every named, non-ramp color in the client's naming) and ``languages``
    (from the project's HTML, most used first). Files ux-skill wrote itself
    (a MASTER.md or DESIGN.md it owns) are not an existing system.
    """
    base = Path(root).expanduser()
    result: Dict[str, Any] = {"found": False, "root": str(base.resolve()) if base.exists() else str(base),
                              "sources": [], "declared": {}}
    if not base.is_dir():
        return result

    sources: List[Dict[str, str]] = []

    def add(kind: str, path: Path) -> None:
        rel = path.relative_to(base).as_posix() if path != base else "."
        entry = {"kind": kind, "path": rel}
        if entry not in sources:
            sources.append(entry)

    # Only the root's own files and the conventional system folders are read,
    # so a repository that merely hosts example systems in docs/ is not one.
    system_dirs: List[str] = list(_SYSTEM_DIRS)
    packages = base / "packages"
    if packages.is_dir():
        for child in sorted(packages.iterdir()):
            rel = "packages/" + child.name
            if child.is_dir() and rel not in system_dirs and any(
                    w in child.name.lower() for w in _PACKAGE_WORDS):
                system_dirs.append(rel)
    seen: set = set()
    files: List[Path] = [p for p in sorted(base.iterdir()) if p.is_file()] if base.is_dir() else []
    for rel in system_dirs:
        if (base / rel).is_dir():
            _walk(base / rel, 1, seen, files)
    html_files: List[Path] = []
    _walk(base, 0, set(), html_files)

    for rel in system_dirs:
        d = base / rel
        if (rel in ("design-system", "design-tokens", "tokens") or rel.startswith("packages/")) \
                and d.is_dir() and any(d.iterdir()):
            add("system-folder", d)

    token_docs: List[Tuple[Path, Any]] = []
    css_files: List[Path] = []
    for path in files:
        name = path.name
        rel_parts = path.relative_to(base).parts
        in_system_dir = len(rel_parts) > 1
        if _TOKEN_FILE_RE.search(name) or (in_system_dir and name.lower().endswith(".json")):
            doc = _looks_dtcg(path)
            if doc is not None:
                token_docs.append((path, doc))
                add("tokens", path)
                continue
        if _BUILD_SCRIPT_RE.match(name) and (in_system_dir or "token" in path.as_posix().lower()):
            add("build-script", path)
            continue
        if name.lower().endswith(".css"):
            parent_words = {p.lower() for p in rel_parts[:-1]}
            if _FOUNDATION_CSS_RE.search(name) or parent_words & {"foundation", "foundations", "tokens"}:
                if len(css_custom_properties(_read_text(path))) >= 3:
                    css_files.append(path)
                    add("css-foundation", path)

    for script in _package_token_scripts(base):
        add("build-script", base / "package.json")
        break

    for cand in (base / "MASTER.md", base / "design-system" / "MASTER.md",
                 base / ".ux" / "design-system" / "MASTER.md"):
        if cand.is_file() and not is_ux_skill_file(cand):
            add("master-md", cand)
    for cand in (base / "DESIGN.md", base / "design-system" / "DESIGN.md"):
        if cand.is_file() and not is_ux_skill_file(cand):
            add("design-md", cand)

    # ---- what the system declares
    colors: List[Tuple[str, str]] = []
    font_tokens: List[Tuple[str, str]] = []
    for _path, doc in token_docs:
        for name, tok in flatten_dtcg(doc).items():
            typ = str(tok.get("type") or "").lower()
            if typ == "color" or (not typ and normalize_hex(tok["value"])):
                hx = normalize_hex(tok["value"])
                if hx:
                    colors.append((name, hx))
            elif typ in ("fontfamily", "font-family") or "family" in _segments(name):
                font_tokens.append((name, _first_family(tok["value"])))

    css_props: Dict[str, str] = {}
    for path in css_files:
        for k, v in css_custom_properties(_read_text(path)).items():
            css_props.setdefault(k, v)
    css_colors: List[Tuple[str, str]] = []
    css_fonts: List[Tuple[str, str]] = []
    for name, value in css_props.items():
        resolved = resolve_css_var(value, css_props)
        hx = normalize_hex(resolved)
        if hx:
            css_colors.append((name.lstrip("-"), hx))
        elif "font" in name and ("family" in name or "face" in name or name.endswith("font")):
            css_fonts.append((name.lstrip("-"), _first_family(resolved)))

    declared: Dict[str, Any] = {}
    p_name, p_hex = _rank_primary(colors)
    p_from = "tokens"
    if not p_hex:
        p_name, p_hex = _rank_primary(css_colors)
        p_from = "css"
        if p_name:
            p_name = "--" + p_name
    if p_hex:
        declared["primary"] = p_hex
        declared["primary_token"] = p_name
        declared["primary_from"] = p_from
    t_name, t_hex = _rank_text(colors)
    if not t_hex:
        t_name, t_hex = _rank_text(css_colors)
        if t_name:
            t_name = "--" + t_name
    if t_hex:
        declared["text"] = t_hex
        declared["text_token"] = t_name
    fonts = _fonts_from(font_tokens) or _fonts_from(css_fonts)
    if fonts:
        declared["fonts"] = fonts
    named: Dict[str, str] = {}
    for name, hx in (colors or [("--" + n, h) for n, h in css_colors]):
        segs = _segments(name)
        if segs and not segs[-1].isdigit():
            named.setdefault("-".join(segs), hx)
    if named:
        declared["colors"] = named
    langs = _html_languages(html_files)
    if langs:
        declared["languages"] = langs

    order = {"tokens": 0, "build-script": 1, "css-foundation": 2, "master-md": 3,
             "design-md": 4, "system-folder": 5}
    sources.sort(key=lambda s: order.get(s["kind"], 9))
    result["sources"] = sources
    result["declared"] = declared
    result["found"] = bool(sources)
    return result
