"""Find an existing design system in a project and read what it declares.

Deterministic and offline. Reads files only; never runs the project's
build script and never writes.
"""
from __future__ import annotations

import colorsys
import hashlib
import json
import math
import re
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple

# The frontmatter key and value ux-skill writes into a MASTER.md it owns.
OWNER_KEY = "generated_by"
OWNER_VALUE = "ux-skill"
# The phrase `ux design-md` writes into every DESIGN.md it creates.
DESIGN_MD_MARKER = "Generated by ux-skill"
# A file ux-skill writes carries a digest of its own text. It stays ux-skill's
# only while the text still matches: a hand edit makes it the person's file.
DIGEST_KEY = "ux_skill_digest"
_DIGEST_LINE_RE = re.compile(r"^(?:#\s*)?ux[_-]skill[_-]digest:\s*([0-9a-f]{64})[ \t]*\n?",
                             re.MULTILINE)
# The exact shape MASTER.md had before the digest existed.
_LEGACY_MASTER_HEADING = "# Design system \u2014 MASTER"
_LEGACY_KEY_SETS = ({"project", "last_updated", "ux_skill_version"},
                    {"project", "page", "last_updated", "ux_skill_version"})

# Folders a design system conventionally lives in, relative to the root.
_SYSTEM_DIRS = (
    "design-system", "design-tokens", "tokens", "packages/tokens", "packages/design-tokens",
    "packages/foundation", "packages/foundations", "packages/design-system",
    "src/tokens", "src/design-system", "src/theme", "theme", "styles", "src/styles", "src/css",
    "app/styles", "css", "assets/css", "assets/styles", "static/css", "public/css",
)
# A folder under packages/ whose name holds one of these words is a system folder too.
_PACKAGE_WORDS = ("token", "design", "foundation", "theme", "style")
_SKIP_DIRS = {"node_modules", ".git", ".ux", ".venv", "venv", "__pycache__", ".next",
              ".claude", ".cache", "vendor"}
_BUILT_DIRS = {"build", "dist", "out", "generated", ".generated"}
_MAX_DEPTH = 4
_MAX_FILES = 4000

_TOKEN_FILE_RE = re.compile(r"^(?:design-)?tokens(?:\.[\w-]+)?\.json$|\.tokens\.json$", re.I)
_BUILD_SCRIPT_RE = re.compile(
    r"^(?:build(?:-tokens)?|resolve[\w-]*|resolver|style-dictionary\.config|sd\.config|"
    r"tokens\.config)\.(?:mjs|cjs|js|ts|py)$", re.I)
_SD_CONFIG_RE = re.compile(r"^(?:style-dictionary|sd|tokens)\.config\.(?:mjs|cjs|js|ts|json)$", re.I)
_SCRIPT_JSON_RE = re.compile(r"[\"'`]([^\"'`\n]+?\.json)[\"'`]")
_TOKEN_SCRIPT_KEY_RE = re.compile(r"(?:^|[:_-])(?:design-)?tokens(?:$|[:_-])", re.I)
_GENERATED_RE = re.compile(r"generated\b.{0,200}?\bdo not edit|do not edit.{0,200}?\bgenerated",
                           re.I | re.S)
_FOUNDATION_CSS_RE = re.compile(r"(?:^|[-_.])(?:foundations?|tokens|variables|theme)\.css$", re.I)
_CUSTOM_PROP_RE = re.compile(r"(--[A-Za-z0-9_-]+)\s*:\s*([^;{}]+)")
_HTML_LANG_RE = re.compile(r"<html\b[^>]*\blang\s*=\s*['\"]([A-Za-z]{2,3})(?:-[A-Za-z0-9-]+)?['\"]", re.I)
_HTML_RTL_RE = re.compile(r"<html\b[^>]*\bdir\s*=\s*['\"]rtl['\"]", re.I)
_HEX_RE = re.compile(r"^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$")
_FUNC_RE = re.compile(r"^(rgba?|hsla?|oklch|oklab|color)\(\s*(.*?)\s*\)$", re.I | re.S)
_DIMENSION_RE = re.compile(r"^-?\d+(?:\.\d+)?(?:px|rem|em|%|pt|vw|vh|ms|s)$")

_PRIMARY_WORDS = {"primary", "brand"}
_NOT_PRIMARY = {
    "hover", "pressed", "active", "focus", "disabled", "on", "subtle", "muted", "soft",
    "container", "text", "fg", "foreground", "ink", "border", "outline", "inverse", "weak",
    "strong", "dark", "tint", "shade", "alpha", "variant", "secondary", "tertiary", "bg",
    "background", "surface", "light", "faint", "ring", "shadow", "canvas", "page", "paper",
    "neutral", "gray", "grey", "danger", "error", "success", "warning", "info", "critical",
    "hairline", "divider", "overlay", "scrim",
}
_TEXT_WORDS = {"text", "ink", "fg", "foreground", "content"}
# Words that make a text-ish token something other than the page's text:
# a state, an inverse, and the status and promotion groups (a sale red's fg).
_NOT_TEXT = {
    "on", "inverse", "disabled", "link", "accent", "muted", "secondary", "tertiary", "subtle",
    "placeholder", "hover", "danger", "error", "success", "warning", "info", "critical",
    "alert", "dark", "weak", "faint", "selection", "offer", "deal", "promo", "sale", "status",
    "badge", "tag", "positive", "negative", "notice", "highlight",
}
_TEXT_BEST = {"primary", "default", "base", "strong", "body", "main"}
_TEXT_MAX_CHROMA = 0.35    # a text color is near-neutral
_TEXT_MIN_CONTRAST = 4.5   # on white or the declared canvas
_DISPLAY_WORDS = {"display", "heading", "headline", "head", "title"}
_BODY_WORDS = {"body", "base", "text", "sans", "default", "ui", "copy"}

# Kinds that make a system on their own; the rest are hints.
_STRONG_KINDS = {"tokens-source", "tokens", "built-output", "css-foundation", "master-md",
                 "design-md"}
_KIND_ORDER = {"tokens-source": 0, "tokens": 1, "css-foundation": 2, "built-output": 3,
               "master-md": 4, "design-md": 5, "build-script": 6, "system-folder": 7}


# ------------------------------------------------------------------ color


def _num(text: str, percent_scale: float = 1.0) -> float:
    """A CSS number; a percentage is scaled so 100% equals ``percent_scale``."""
    t = text.strip().lower()
    if t in ("none", ""):
        return 0.0
    if t.endswith("%"):
        return float(t[:-1]) / 100.0 * percent_scale
    for unit in ("deg", "turn", "rad", "grad"):
        if t.endswith(unit):
            v = float(t[:-len(unit)])
            return {"deg": v, "turn": v * 360, "rad": math.degrees(v), "grad": v * 0.9}[unit]
    return float(t)


def _rgb_hex(r: float, g: float, b: float) -> str:
    return "#%02X%02X%02X" % tuple(max(0, min(255, int(round(c)))) for c in (r, g, b))


def _oklch_hex(L: float, C: float, H: float) -> str:
    # CSS Color 4 gamut mapping, the same the importers' value reader uses.
    from engine.foundations.color_math import gamut_map_oklch
    return gamut_map_oklch(L, C, H)[0]


def _hsl_hex(h: float, s: float, l: float) -> str:
    r, g, b = colorsys.hls_to_rgb((h % 360) / 360.0, max(0.0, min(1.0, l)), max(0.0, min(1.0, s)))
    return _rgb_hex(r * 255, g * 255, b * 255)


def _function_hex(name: str, args: str) -> str:
    parts = [p for p in re.split(r"[\s,/]+", args.strip()) if p]
    try:
        if name in ("rgb", "rgba") and len(parts) >= 3:
            return _rgb_hex(*(_num(p, 255.0) for p in parts[:3]))
        if name in ("hsl", "hsla") and len(parts) >= 3:
            return _hsl_hex(_num(parts[0]), _num(parts[1], 1.0) if parts[1].endswith("%")
                            else float(parts[1]) / 100.0,
                            _num(parts[2], 1.0) if parts[2].endswith("%")
                            else float(parts[2]) / 100.0)
        if name == "oklch" and len(parts) >= 3:
            return _oklch_hex(_num(parts[0], 1.0), _num(parts[1], 0.4), _num(parts[2]))
        if name == "oklab" and len(parts) >= 3:
            L, a, b = _num(parts[0], 1.0), _num(parts[1], 0.4), _num(parts[2], 0.4)
            return _oklch_hex(L, math.hypot(a, b), math.degrees(math.atan2(b, a)) % 360)
        if name == "color" and len(parts) >= 4 and parts[0].lower() == "srgb":
            return _rgb_hex(*(_num(p, 1.0) * 255 for p in parts[1:4]))
    except (ValueError, ImportError):
        return ""
    return ""


def normalize_hex(value: Any) -> str:
    """A color as #RRGGBB upper case, or "" when it is not a color this can
    read. Reads hex, rgb(), hsl(), oklch(), oklab(), color(srgb ...) and the
    DTCG color object (hex, or components in srgb, hsl, oklch or oklab)."""
    if isinstance(value, dict):
        hx = value.get("hex")
        if isinstance(hx, str):
            return normalize_hex(hx)
        comps = value.get("components")
        space = str(value.get("colorSpace") or "srgb").lower()
        if isinstance(comps, list) and len(comps) >= 3:
            try:
                c = [0.0 if x in (None, "none") else float(x) for x in comps[:3]]
            except (TypeError, ValueError):
                return ""
            try:
                if space == "srgb":
                    return _rgb_hex(*(x * 255 for x in c))
                if space == "hsl":
                    return _hsl_hex(c[0], c[1] / 100.0, c[2] / 100.0)
                if space == "oklch":
                    return _oklch_hex(*c)
                if space == "oklab":
                    return _oklch_hex(c[0], math.hypot(c[1], c[2]),
                                      math.degrees(math.atan2(c[2], c[1])) % 360)
            except (ValueError, ImportError):
                return ""
        return ""
    if not isinstance(value, str):
        return ""
    s = value.strip()
    m = _FUNC_RE.match(s)
    if not (m or _HEX_RE.match(s)):
        return ""
    # The importers' value reader first, so detect and import read one color
    # the same way. What it refuses by design (color(srgb), loose syntax)
    # detect still reads leniently, to find a primary.
    from engine.io.values_in import NotRead, read_value  # engine.io imports this package
    try:
        kind, hx = read_value(s)
        if kind == "color":
            return hx[:7]
    except NotRead:
        pass
    return _function_hex(m.group(1).lower(), m.group(2)) if m else ""


def _segments(path: str) -> List[str]:
    return [s for s in re.split(r"[.\-_/\s]+", path.lower()) if s]


def _read_text(path: Path, limit: int = 2_000_000) -> str:
    try:
        data = path.read_bytes()[:limit]
    except OSError:
        return ""
    return data.decode("utf-8", errors="ignore")


def _parse_frontmatter(text: str) -> Tuple[Dict[str, str], str]:
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}, text
    meta: Dict[str, str] = {}
    for idx, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            return meta, "\n".join(lines[idx + 1:])
        m = re.match(r"^([A-Za-z0-9_]+)\s*:\s*(.*)$", line)
        if m:
            meta[m.group(1)] = m.group(2).strip().strip('"').strip("'")
    return {}, text


# ------------------------------------------------------------------ ownership


def text_digest(text: str) -> str:
    """The sha256 of ``text`` without its digest line."""
    return hashlib.sha256(_DIGEST_LINE_RE.sub("", text).encode("utf-8")).hexdigest()


def stamp_digest(text: str, comment: bool = False) -> str:
    """``text`` with a digest line added after its opening ``---``: a
    frontmatter key, or a YAML comment when ``comment`` is True (for a
    DESIGN.md, whose frontmatter keys are a fixed standard)."""
    digest = text_digest(text)
    line = ("# ux-skill-digest: %s\n" if comment else DIGEST_KEY + ": %s\n") % digest
    if text.startswith("---\n"):
        return "---\n" + line + text[4:]
    return line + text


def ownership(path: Any) -> str:
    """Who a file belongs to: ``missing``; ``owned`` (ux-skill wrote it and
    it is unchanged); ``edited`` (ux-skill wrote it, then a person changed
    it); ``legacy`` (the exact shape ux-skill wrote before the digest
    existed); ``foreign`` (anything else, such as a hand-written file)."""
    p = Path(path)
    if not p.is_file():
        return "missing"
    text = _read_text(p)
    m = _DIGEST_LINE_RE.search(text)
    if m:
        return "owned" if m.group(1) == text_digest(text) else "edited"
    meta, body = _parse_frontmatter(text)
    first = next((ln for ln in body.splitlines() if ln.strip()), "").strip()
    if set(meta) in _LEGACY_KEY_SETS and (first == _LEGACY_MASTER_HEADING
                                         or first.startswith("# Page \u2014 ")):
        return "legacy"
    if p.suffix.lower() == ".md" and DESIGN_MD_MARKER in text and text.startswith("---"):
        return "legacy"
    return "foreign"


def is_ux_skill_file(path: Any) -> bool:
    """True only while ux-skill's own digest still matches the file: a file
    it wrote and nobody has changed since. Safe to overwrite."""
    return ownership(path) == "owned"


# ------------------------------------------------------------------ DTCG


def _is_token(node: Any) -> bool:
    if not isinstance(node, dict):
        return False
    if "$value" in node:
        return True
    return "value" in node and not isinstance(node.get("value"), dict) and (
        "type" in node or set(node) <= {"value", "type", "description", "comment"})


def flatten_dtcg(doc: Any) -> Dict[str, Dict[str, Any]]:
    """Every token in a DTCG (or Tokens Studio) document as
    ``{dotted.path: {"type": ..., "value": resolved}}``. References such as
    ``{color.blue.500}`` are resolved; a reference that cannot be resolved
    keeps its text."""
    raw: Dict[str, Dict[str, Any]] = {}

    def walk(node: Any, path: List[str], inherited: Optional[str]) -> None:
        if not isinstance(node, dict):
            return
        typ = (node.get("$type") or node.get("type")) if _is_token(node) else node.get("$type")
        typ = typ or inherited
        if _is_token(node):
            value = node.get("$value", node.get("value"))
            raw[".".join(path)] = {"type": typ or "", "value": value}
            return
        for key, child in node.items():
            if key.startswith("$"):
                continue
            walk(child, path + [key], typ)

    walk(doc, [], None)

    def resolve(value: Any, depth: int = 0) -> Any:
        if depth > 24:
            return value
        if isinstance(value, str):
            m = re.fullmatch(r"\{([^{}]+)\}", value.strip())
            if m and m.group(1) in raw:
                return resolve(raw[m.group(1)]["value"], depth + 1)
        return value

    out: Dict[str, Dict[str, Any]] = {}
    for key, tok in raw.items():
        value = resolve(tok["value"])
        typ = tok["type"]
        if not typ and normalize_hex(value):
            typ = "color"
        out[key] = {"type": typ, "value": value}
    return out


def _is_design_token(tok: Dict[str, Any]) -> bool:
    """A color or a dimension: what a design token file holds and an API
    key file does not."""
    typ = str(tok.get("type") or "").lower()
    value = tok.get("value")
    if typ in ("color", "dimension", "fontsize", "spacing", "sizing", "borderradius"):
        return True
    if normalize_hex(value):
        return True
    if isinstance(value, dict) and "unit" in value and "value" in value:
        return True
    return isinstance(value, str) and bool(_DIMENSION_RE.match(value.strip()))


def _rank_primary(names: Iterable[Tuple[str, str]]) -> Tuple[str, str]:
    best: Optional[Tuple[Tuple[int, int, int], str, str]] = None
    for order, (name, hx) in enumerate(names):
        segs = _segments(name)
        if not hx or not segs or segs[-1].isdigit():
            continue
        words = set(segs)
        hits = words & _PRIMARY_WORDS
        if not hits or words & _NOT_PRIMARY:
            continue
        score = (-len(hits), len(segs), order)
        if best is None or score < best[0]:
            best = (score, name, hx)
    return (best[1], best[2]) if best else ("", "")


def _luminance(hx: str) -> float:
    def ch(c: int) -> float:
        c = c / 255.0
        return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4
    r, g, b = (int(hx[i:i + 2], 16) for i in (1, 3, 5))
    return 0.2126 * ch(r) + 0.7152 * ch(g) + 0.0722 * ch(b)


def _contrast(a: str, b: str) -> float:
    la, lb = sorted((_luminance(a), _luminance(b)), reverse=True)
    return (la + 0.05) / (lb + 0.05)


def _chroma(hx: str) -> float:
    r, g, b = (int(hx[i:i + 2], 16) for i in (1, 3, 5))
    hi, lo = max(r, g, b), min(r, g, b)
    return 0.0 if hi == 0 else (hi - lo) / hi


def _rank_text(names: Iterable[Tuple[str, str]], canvas: str = "") -> Tuple[str, str]:
    """The page's text color, read by role name. A text word followed by a
    base word (``text.default``, ``text.primary``, ``fg.base``) ranks first,
    then a name ending in a text word, then any other text name. Status and
    promotion groups (offer, sale, danger, ...) never qualify, and a
    candidate must be near-neutral and reach 4.5:1 on white or the canvas."""
    best: Optional[Tuple[Tuple[int, int, int], str, str]] = None
    grounds = ["#FFFFFF"] + ([canvas] if canvas else [])
    for order, (name, hx) in enumerate(names):
        segs = _segments(name)
        if not hx or not segs or segs[-1].isdigit():
            continue
        words = set(segs)
        if not words & _TEXT_WORDS or words & _NOT_TEXT:
            continue
        if _chroma(hx) > _TEXT_MAX_CHROMA or max(_contrast(hx, g) for g in grounds) < _TEXT_MIN_CONTRAST:
            continue
        paired = any(a in _TEXT_WORDS and b in _TEXT_BEST for a, b in zip(segs, segs[1:]))
        tier = 0 if paired else (1 if segs[-1] in _TEXT_WORDS else 2)
        score = (tier, len(segs), order)
        if best is None or score < best[0]:
            best = (score, name, hx)
    return (best[1], best[2]) if best else ("", "")


def _canvas(names: Iterable[Tuple[str, str]]) -> str:
    for name, hx in names:
        segs = _segments(name)
        if segs and segs[-1] in ("canvas", "page", "background"):
            return hx
    return ""


def _first_family(value: Any) -> str:
    if isinstance(value, list):
        value = value[0] if value else ""
    if not isinstance(value, str):
        return ""
    return value.split(",")[0].strip().strip('"').strip("'")


def _fonts_from(names: Iterable[Tuple[str, str]]) -> Dict[str, str]:
    display = body = ""
    for name, family in names:
        if not family:
            continue
        words = set(_segments(name))
        if not display and words & _DISPLAY_WORDS:
            display = family
        elif not body and (words & _BODY_WORDS or not words & _DISPLAY_WORDS):
            body = family
    fonts: Dict[str, str] = {}
    if display or body:
        fonts = {"display": display or body, "body": body or display}
    return fonts


# ------------------------------------------------------------------ CSS


def css_custom_properties(text: str) -> Dict[str, str]:
    """Every ``--name: value`` declaration in CSS text, first one wins."""
    text = re.sub(r"/\*.*?\*/", "", text or "", flags=re.S)
    props: Dict[str, str] = {}
    for m in _CUSTOM_PROP_RE.finditer(text):
        props.setdefault(m.group(1), m.group(2).strip())
    return props


def resolve_css_var(value: str, props: Dict[str, str], depth: int = 0) -> str:
    """Follow ``var(--x)`` chains to the final value (fallbacks honored)."""
    if depth > 24 or not isinstance(value, str):
        return value or ""
    # One reader of a var() reference: the importers' css_alias.
    from engine.io.values_in import NotRead, css_alias  # engine.io imports this package
    try:
        ref = css_alias(value)
    except NotRead:
        ref = None
    if ref is None:
        return value.strip()
    name, fallback = "--" + ref[0], ref[1]
    if name in props:
        return resolve_css_var(props[name], props, depth + 1)
    return resolve_css_var(fallback, props, depth + 1) if fallback else ""


# ------------------------------------------------------------------ walk


def _walk(base: Path, depth: int, seen: set, out: List[Path]) -> None:
    if depth > _MAX_DEPTH or len(out) >= _MAX_FILES:
        return
    try:
        entries = sorted(base.iterdir())
    except OSError:
        return
    for entry in entries:
        if entry.name in _SKIP_DIRS or entry.is_symlink():
            continue
        if entry.is_dir():
            _walk(entry, depth + 1, seen, out)
        elif entry.is_file():
            key = str(entry.resolve())
            if key not in seen:
                seen.add(key)
                out.append(entry)


def _token_doc(path: Path) -> Optional[Any]:
    """The JSON document when it is a design token file: it flattens to at
    least one color or dimension token."""
    text = _read_text(path)
    if '"$value"' not in text and '"value"' not in text:
        return None
    try:
        doc = json.loads(text)
    except ValueError:
        return None
    if not isinstance(doc, dict):
        return None
    return doc if any(_is_design_token(t) for t in flatten_dtcg(doc).values()) else None


def _is_built(path: Path, base: Path) -> bool:
    """Generated output: under a build/dist/out folder, or headed
    "Generated ... Do not edit"."""
    parts = {p.lower() for p in path.relative_to(base).parts[:-1]}
    if parts & _BUILT_DIRS:
        return True
    return bool(_GENERATED_RE.search(_read_text(path, 600)))


def _script_sources(script: Path, base: Path) -> List[Path]:
    """The .json files a build script names that exist inside the project,
    resolved against the script's folder."""
    out: List[Path] = []
    for ref in _SCRIPT_JSON_RE.findall(_read_text(script, 200_000)):
        if re.match(r"^[a-z][a-z0-9+.-]*://", ref, re.I) or "package.json" in ref:
            continue
        cand = (script.parent / ref)
        try:
            cand = cand.resolve()
            cand.relative_to(base.resolve())
        except (OSError, ValueError):
            continue
        if cand.is_file() and cand not in out:
            out.append(cand)
    return out


def _package_token_scripts(root: Path) -> List[str]:
    pkg = root / "package.json"
    if not pkg.is_file():
        return []
    try:
        scripts = (json.loads(_read_text(pkg)) or {}).get("scripts") or {}
    except (ValueError, AttributeError):
        return []
    if not isinstance(scripts, dict):
        return []
    return sorted(k for k, v in scripts.items()
                  if _TOKEN_SCRIPT_KEY_RE.search(k)
                  or "style-dictionary" in str(v) or "token-transformer" in str(v))


def _html_languages(files: List[Path]) -> List[str]:
    counts: Dict[str, List[int]] = {}
    for order, path in enumerate(files):
        if path.suffix.lower() not in (".html", ".htm"):
            continue
        head = _read_text(path, 20_000)
        m = _HTML_LANG_RE.search(head)
        if not m:
            continue
        lang = m.group(1).lower()
        rec = counts.setdefault(lang, [0, 0, order])
        rec[0] += 1
        if _HTML_RTL_RE.search(head):
            rec[1] += 1
    return [lang for lang, _ in sorted(counts.items(),
                                       key=lambda kv: (-kv[1][0], -kv[1][1], kv[1][2]))]


def _read_colors(docs: List[Any]) -> Tuple[List[Tuple[str, str]], List[Tuple[str, str]],
                                           List[Tuple[str, str]]]:
    """(colors read as hex, font families, color values that could not be read)."""
    colors: List[Tuple[str, str]] = []
    fonts: List[Tuple[str, str]] = []
    raw: List[Tuple[str, str]] = []
    for doc in docs:
        for name, tok in flatten_dtcg(doc).items():
            typ = str(tok.get("type") or "").lower()
            if typ == "color" or (not typ and normalize_hex(tok["value"])):
                hx = normalize_hex(tok["value"])
                if hx:
                    colors.append((name, hx))
                elif isinstance(tok["value"], str):
                    raw.append((name, tok["value"].strip()))
            elif typ in ("fontfamily", "font-family") or "family" in _segments(name):
                fonts.append((name, _first_family(tok["value"])))
    return colors, fonts, raw


def detect_existing_system(root: Any = ".") -> Dict[str, Any]:
    """Find an existing design system under ``root`` and read what it declares.

    Returns ``{"found", "root", "sources", "hints", "declared"}``.

    ``sources`` lists each file or folder of the system as ``{"kind", "path"}``
    (path relative to ``root``), the token source first. Kinds:
    ``tokens-source`` (a token file a build script reads), ``tokens`` (a DTCG
    or tokens JSON file), ``css-foundation``, ``built-output`` (generated
    files under build/, dist/ or out/, or headed "Generated ... Do not
    edit"; never edit these), ``master-md``, ``design-md``, ``build-script``
    and ``system-folder``.

    ``found`` is true only on a strong signal: a token file holding at least
    one color or dimension, a foundation CSS file, or a hand-written MASTER.md
    or DESIGN.md. A file ux-skill wrote and a person then edited is not a
    system: commands write beside it instead of over it. A folder, a build script or a
    package script alone is reported under ``hints`` and is not a system.

    ``declared`` is read from the token source first, then other token
    files, then built output, then foundation CSS: ``primary`` and
    ``primary_token`` (or ``primary_raw`` and ``primary_note`` when the value
    cannot be read), ``text`` and ``text_token``, ``fonts`` ({display,
    body}), ``colors`` (every named, non-ramp color in the client's naming)
    and ``languages`` (from the project's HTML, most used first).
    """
    base = Path(root).expanduser()
    result: Dict[str, Any] = {"found": False,
                              "root": str(base.resolve()) if base.exists() else str(base),
                              "sources": [], "hints": [], "declared": {}}
    if not base.is_dir():
        return result
    base = base.resolve()

    sources: List[Dict[str, str]] = []

    def add(kind: str, path: Path) -> None:
        rel = path.relative_to(base).as_posix() if path != base else "."
        if any(s["path"] == rel for s in sources):
            return
        sources.append({"kind": kind, "path": rel})

    # Only the root's own files and the conventional system folders are read,
    # so a repository that merely hosts example systems in docs/ is not one.
    system_dirs: List[str] = list(_SYSTEM_DIRS)
    packages = base / "packages"
    if packages.is_dir():
        for child in sorted(packages.iterdir()):
            rel = "packages/" + child.name
            if child.is_dir() and rel not in system_dirs and any(
                    w in child.name.lower() for w in _PACKAGE_WORDS):
                system_dirs.append(rel)
    seen: set = set()
    files: List[Path] = [p for p in sorted(base.iterdir()) if p.is_file()]
    for rel in system_dirs:
        if (base / rel).is_dir():
            _walk(base / rel, 1, seen, files)
    html_files: List[Path] = []
    _walk(base, 0, set(), html_files)

    # Token sources: the .json files a token build script reads.
    scripts = [p for p in files
               if (_BUILD_SCRIPT_RE.match(p.name) and "token" in p.relative_to(base).as_posix().lower())
               or _SD_CONFIG_RE.match(p.name)]
    source_docs: List[Any] = []
    for script in scripts:
        for src in _script_sources(script, base):
            doc = _token_doc(src)
            if doc is not None:
                source_docs.append(doc)
                add("tokens-source", src)

    token_docs: List[Any] = []
    built_docs: List[Any] = []
    css_files: List[Path] = []
    built_css: List[Path] = []
    for path in files:
        name = path.name
        rel_parts = path.relative_to(base).parts
        if any(s["path"] == path.relative_to(base).as_posix() for s in sources):
            continue
        if _TOKEN_FILE_RE.search(name) or (len(rel_parts) > 1 and name.lower().endswith(".json")):
            doc = _token_doc(path)
            if doc is not None:
                if _is_built(path, base):
                    built_docs.append(doc)
                    add("built-output", path)
                else:
                    token_docs.append(doc)
                    add("tokens", path)
                continue
        if path in scripts:
            add("build-script", path)
            continue
        if name.lower().endswith(".css"):
            parent_words = {p.lower() for p in rel_parts[:-1]}
            if _FOUNDATION_CSS_RE.search(name) or parent_words & {"foundation", "foundations", "tokens"}:
                if len(css_custom_properties(_read_text(path))) >= 3:
                    if _is_built(path, base):
                        built_css.append(path)
                        add("built-output", path)
                    else:
                        css_files.append(path)
                        add("css-foundation", path)

    if _package_token_scripts(base):
        add("build-script", base / "package.json")

    for cand in (base / "MASTER.md", base / "design-system" / "MASTER.md",
                 base / ".ux" / "design-system" / "MASTER.md"):
        if ownership(cand) == "foreign":
            add("master-md", cand)
    for cand in (base / "DESIGN.md", base / "design-system" / "DESIGN.md"):
        if ownership(cand) == "foreign":
            add("design-md", cand)

    for rel in system_dirs:
        d = base / rel
        if (rel in ("design-system", "design-tokens", "tokens") or rel.startswith("packages/")) \
                and d.is_dir() and any(d.iterdir()):
            add("system-folder", d)

    sources.sort(key=lambda s: _KIND_ORDER.get(s["kind"], 9))
    if not any(s["kind"] in _STRONG_KINDS for s in sources):
        result["hints"] = sources
        return result

    # ---- what the system declares: the source first, generated output last
    colors: List[Tuple[str, str]] = []
    font_tokens: List[Tuple[str, str]] = []
    raw_colors: List[Tuple[str, str]] = []
    for tier in (source_docs, token_docs, built_docs):
        if tier:
            colors, font_tokens, raw_colors = _read_colors(tier)
            if colors:
                break

    css_props: Dict[str, str] = {}
    for path in css_files + built_css:
        for k, v in css_custom_properties(_read_text(path)).items():
            css_props.setdefault(k, v)
    css_colors: List[Tuple[str, str]] = []
    css_fonts: List[Tuple[str, str]] = []
    for name, value in css_props.items():
        resolved = resolve_css_var(value, css_props)
        hx = normalize_hex(resolved)
        if hx:
            css_colors.append((name.lstrip("-"), hx))
        elif "font" in name and ("family" in name or "face" in name or name.endswith("font")):
            css_fonts.append((name.lstrip("-"), _first_family(resolved)))

    declared: Dict[str, Any] = {}
    p_name, p_hex = _rank_primary(colors)
    p_from = "tokens"
    if not p_hex:
        p_name, p_hex = _rank_primary(css_colors)
        p_from = "css"
        if p_name:
            p_name = "--" + p_name
    if p_hex:
        declared["primary"] = p_hex
        declared["primary_token"] = p_name
        declared["primary_from"] = p_from
    else:
        r_name, r_value = _rank_primary((n, v) for n, v in raw_colors)
        if r_name:
            declared["primary_raw"] = r_value
            declared["primary_token"] = r_name
            declared["primary_note"] = (
                "%s is %s, a color this cannot convert to hex; read it from the system and "
                "pass it as the brand primary by hand." % (r_name, r_value))
    t_name, t_hex = _rank_text(colors, _canvas(colors))
    if not t_hex:
        t_name, t_hex = _rank_text(css_colors, _canvas(css_colors))
        if t_name:
            t_name = "--" + t_name
    if t_hex:
        declared["text"] = t_hex
        declared["text_token"] = t_name
    fonts = _fonts_from(font_tokens) or _fonts_from(css_fonts)
    if fonts:
        declared["fonts"] = fonts
    named: Dict[str, str] = {}
    for name, hx in (colors or [("--" + n, h) for n, h in css_colors]):
        segs = _segments(name)
        if segs and not segs[-1].isdigit():
            named.setdefault("-".join(segs), hx)
    if named:
        declared["colors"] = named
    langs = _html_languages(html_files)
    if langs:
        declared["languages"] = langs

    result["sources"] = sources
    result["declared"] = declared
    result["found"] = True
    return result


def mark_suggestions(payload: Dict[str, Any], found: Optional[Dict[str, Any]]) -> Dict[str, Any]:
    """``payload`` (an engine result) marked as suggestions when ``found`` is
    an existing system: ``status: suggestion`` plus the ``existing_system``
    block, so no caller mistakes the engine's picks for the project's own."""
    if not found or not found.get("found"):
        return payload
    return {**payload, "status": "suggestion",
            "existing_system": {"root": found.get("root", ""),
                                "sources": list(found.get("sources") or []),
                                "declared": dict(found.get("declared") or {})}}


def client_files_in(out_dir: Any, files: Any) -> List[str]:
    """Of the files a ux-skill build would write into ``out_dir`` (a mapping
    of name to text, or names), the ones that already exist there with other
    content, when ``out_dir`` holds a client's design system (what
    ``detect_existing_system`` finds). A folder whose tokens.json carries
    ux-skill's own extension key is ux-skill's, and a folder that is not a
    system holds no client files."""
    out = Path(out_dir)
    tokens = out / "tokens.json"
    if tokens.is_file() and "io.github.laith0003.ux-skill" in _read_text(tokens):
        return []
    if not out.is_dir() or not detect_existing_system(out).get("found"):
        return []
    theirs = []
    for name in files:
        path = out / name
        if not path.is_file():
            continue
        if hasattr(files, "keys") and _read_text(path) == files[name]:
            continue
        theirs.append(name)
    return sorted(theirs)
