"""Find an existing design system in a project and read what it declares.

Deterministic and offline. Reads files only; never runs the project's
build script and never writes.
"""
from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple

from engine.existing import survey
from engine.foundations.color_math import oklab_to_oklch

# The frontmatter key and value ux-skill writes into a MASTER.md it owns.
OWNER_KEY = "generated_by"
OWNER_VALUE = "ux-skill"
# The phrase `ux design-md` writes into every DESIGN.md it creates.
DESIGN_MD_MARKER = "Generated by ux-skill"
# A file ux-skill writes carries a digest of its own text. It stays ux-skill's
# only while the text still matches: a hand edit makes it the person's file.
DIGEST_KEY = "ux_skill_digest"
_DIGEST_LINE_RE = re.compile(r"^(?:#\s*)?ux[_-]skill[_-]digest:\s*([0-9a-f]{64})[ \t]*\n?",
                             re.MULTILINE)
# The exact shape MASTER.md had before the digest existed.
_LEGACY_MASTER_HEADING = "# Design system \u2014 MASTER"
_LEGACY_KEY_SETS = ({"project", "last_updated", "ux_skill_version"},
                    {"project", "page", "last_updated", "ux_skill_version"})

# Folders a design system conventionally lives in, relative to the root.
_SYSTEM_DIRS = (
    "design-system", "design-tokens", "tokens", "packages/tokens", "packages/design-tokens",
    "packages/foundation", "packages/foundations", "packages/design-system",
    "src/tokens", "src/design-system", "src/theme", "theme", "styles", "src/styles", "src/css",
    "app/styles", "css", "assets/css", "assets/styles", "static/css", "public/css",
)
# A folder under packages/ whose name holds one of these words is a system folder too.
_PACKAGE_WORDS = ("token", "design", "foundation", "theme", "style")
_SKIP_DIRS = {"node_modules", ".git", ".ux", ".venv", "venv", "__pycache__", ".next",
              ".claude", ".cache", "vendor"}
_BUILT_DIRS = {"build", "dist", "out", "generated", ".generated"}
_MAX_DEPTH = 4
_MAX_FILES = 4000

_TOKEN_FILE_RE = re.compile(r"^(?:design-)?tokens(?:\.[\w-]+)?\.json$|\.tokens\.json$", re.I)
_BUILD_SCRIPT_RE = re.compile(
    r"^(?:build(?:-tokens)?|resolve[\w-]*|resolver|style-dictionary\.config|sd\.config|"
    r"tokens\.config)\.(?:mjs|cjs|js|ts|py)$", re.I)
_SD_CONFIG_RE = re.compile(r"^(?:style-dictionary|sd|tokens)\.config\.(?:mjs|cjs|js|ts|json)$", re.I)
_SCRIPT_JSON_RE = re.compile(r"[\"'`]([^\"'`\n]+?\.json)[\"'`]")
_TOKEN_SCRIPT_KEY_RE = re.compile(r"(?:^|[:_-])(?:design-)?tokens(?:$|[:_-])", re.I)
_GENERATED_RE = re.compile(r"generated\b.{0,200}?\bdo not edit|do not edit.{0,200}?\bgenerated",
                           re.I | re.S)
_FOUNDATION_CSS_RE = re.compile(r"(?:^|[-_.])(?:foundations?|tokens|variables|theme)\.css$", re.I)
_CUSTOM_PROP_RE = re.compile(r"(--[A-Za-z0-9_-]+)\s*:\s*([^;{}]+)")
_HEX_RE = re.compile(r"^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$")
_FUNC_RE = re.compile(r"^(rgba?|hsla?|oklch|oklab|color)\(\s*(.*?)\s*\)$", re.I | re.S)
_DIMENSION_RE = re.compile(r"^-?\d+(?:\.\d+)?(?:px|rem|em|%|pt|vw|vh|ms|s)$")

_PRIMARY_WORDS = {"primary", "brand"}
# Names an action color goes by when no name says primary or brand.
_ACTION_WORDS = {"accent", "action", "cta", "interactive"}
# Leading words that say a token fills something (bg-brand, color-accent).
_FILL_WORDS = {"color", "colors", "bg", "background", "fill"}
_NOT_PRIMARY = {
    "hover", "pressed", "active", "focus", "disabled", "on", "subtle", "muted", "soft",
    "container", "text", "fg", "foreground", "ink", "border", "outline", "inverse", "weak",
    "strong", "dark", "tint", "shade", "alpha", "variant", "secondary", "tertiary", "bg",
    "background", "surface", "light", "faint", "ring", "shadow", "canvas", "page", "paper",
    "neutral", "gray", "grey", "danger", "error", "success", "warning", "info", "critical",
    "hairline", "divider", "overlay", "scrim",
}
_TEXT_WORDS = {"text", "ink", "fg", "foreground", "content"}
# Words that make a text-ish token something other than the page's text:
# a state, an inverse, and the status and promotion groups (a sale red's fg).
_NOT_TEXT = {
    "on", "inverse", "disabled", "link", "accent", "muted", "secondary", "tertiary", "subtle",
    "placeholder", "hover", "danger", "error", "success", "warning", "info", "critical",
    "alert", "dark", "weak", "faint", "selection", "offer", "deal", "promo", "sale", "status",
    "badge", "tag", "positive", "negative", "notice", "highlight",
}
_TEXT_BEST = {"primary", "default", "base", "strong", "body", "main"}
_TEXT_MAX_CHROMA = 0.35    # a text color is near-neutral
_TEXT_MIN_CONTRAST = 4.5   # on white or the declared canvas
# A near-white (or near-canvas) tint: a hover or surface fill, never the primary.
_TINT_CONTRAST = 1.5
_TINT_CHROMA = 0.2
_DISPLAY_WORDS = {"display", "heading", "headline", "head", "title"}
_BODY_WORDS = {"body", "base", "text", "sans", "default", "ui", "copy"}
# Platform keywords a font list may open with: the face is the system's own.
_PLATFORM_FAMILIES = {"-apple-system", "blinkmacsystemfont", "system-ui", "ui-sans-serif"}

# Kinds that make a system on their own; the rest are hints.
_STRONG_KINDS = {"tokens-source", "tokens", "built-output", "css-foundation", "master-md",
                 "design-md"}
_KIND_ORDER = {"tokens-source": 0, "tokens": 1, "css-foundation": 2, "built-output": 3,
               "master-md": 4, "design-md": 5, "build-script": 6, "system-folder": 7}


# ------------------------------------------------------------------ color


def _num(text: str, percent_scale: float = 1.0) -> float:
    """A CSS number; a percentage is scaled so 100% equals ``percent_scale``."""
    t = text.strip().lower()
    if t in ("none", ""):
        return 0.0
    if t.endswith("%"):
        return float(t[:-1]) / 100.0 * percent_scale
    return float(t)


def _hue(text: str) -> float:
    """A hue in degrees, read by the importers' value reader (a number, or
    an angle in deg, turn, rad or grad). Raises ValueError otherwise."""
    from engine.io.values_in import NotRead, hue_degrees  # engine.io imports this package
    t = text.strip()
    if not t:
        return 0.0
    try:
        return hue_degrees(t)
    except NotRead as exc:
        raise ValueError(str(exc)) from None


def _rgb_hex(r: float, g: float, b: float) -> str:
    return "#%02X%02X%02X" % tuple(max(0, min(255, int(round(c)))) for c in (r, g, b))


def _oklch_hex(L: float, C: float, H: float) -> str:
    # CSS Color 4 gamut mapping, the same the importers' value reader uses.
    from engine.foundations.color_math import gamut_map_oklch
    return gamut_map_oklch(L, C, H)[0]


def _from_hsl(h: float, s: float, light: float) -> str:
    """An hsl color (saturation and lightness from 0 to 1, clamped) as hex,
    converted by the importers' value reader."""
    from engine.io.values_in import hsl_to_rgb  # engine.io imports this package
    return _rgb_hex(*hsl_to_rgb(h, max(0.0, min(1.0, s)), max(0.0, min(1.0, light))))


def _function_hex(name: str, args: str) -> str:
    parts = [p for p in re.split(r"[\s,/]+", args.strip()) if p]
    try:
        if name in ("rgb", "rgba") and len(parts) >= 3:
            return _rgb_hex(*(_num(p, 255.0) for p in parts[:3]))
        if name in ("hsl", "hsla") and len(parts) >= 3:
            return _from_hsl(_hue(parts[0]), _num(parts[1], 1.0) if parts[1].endswith("%")
                             else float(parts[1]) / 100.0,
                             _num(parts[2], 1.0) if parts[2].endswith("%")
                             else float(parts[2]) / 100.0)
        if name == "oklch" and len(parts) >= 3:
            return _oklch_hex(_num(parts[0], 1.0), _num(parts[1], 0.4), _hue(parts[2]))
        if name == "oklab" and len(parts) >= 3:
            L, a, b = _num(parts[0], 1.0), _num(parts[1], 0.4), _num(parts[2], 0.4)
            return _oklch_hex(*oklab_to_oklch(L, a, b))
        if name == "color" and len(parts) >= 4 and parts[0].lower() == "srgb":
            return _rgb_hex(*(_num(p, 1.0) * 255 for p in parts[1:4]))
    except (ValueError, ImportError):
        return ""
    return ""


def normalize_hex(value: Any) -> str:
    """A color as #RRGGBB upper case, or "" when it is not a color this can
    read. Reads hex, rgb(), hsl(), oklch(), oklab(), color(srgb ...) and the
    DTCG color object (hex, or components in srgb, hsl, oklch or oklab)."""
    return normalize_color(value)[:7]


def _alpha_suffix(alpha: Any) -> str:
    """The AA of #RRGGBBAA for an alpha from 0 to 1 (or a percentage), or ""
    when it is opaque or not a number."""
    try:
        a = _num(str(alpha), 1.0)
    except ValueError:
        return ""
    a = max(0.0, min(1.0, a))
    return "" if a >= 1 else "%02X" % round(a * 255)


def normalize_color(value: Any) -> str:
    """A color as #RRGGBB, or #RRGGBBAA when it is translucent (an rgba()
    keeps its alpha), upper case; "" when it is not a color this can read."""
    if isinstance(value, dict):
        hx = _normalize_opaque(value)
        return hx + _alpha_suffix(value.get("alpha", 1)) if hx else ""
    if not isinstance(value, str):
        return ""
    s = value.strip()
    m = _FUNC_RE.match(s)
    if not (m or _HEX_RE.match(s)):
        return ""
    # The importers' value reader first, so detect and import read one color
    # the same way. What it refuses by design (color(srgb), loose syntax)
    # detect still reads leniently, to find a primary.
    from engine.io.values_in import NotRead, read_value  # engine.io imports this package
    try:
        kind, hx = read_value(s)
        if kind == "color":
            return hx
    except NotRead:
        pass
    if not m:
        return ""
    hx = _function_hex(m.group(1).lower(), m.group(2))
    if not hx:
        return ""
    parts = [p for p in re.split(r"[\s,/]+", m.group(2).strip()) if p]
    at = 4 if m.group(1).lower() == "color" else 3
    return hx + (_alpha_suffix(parts[at]) if len(parts) > at else "")


def _normalize_opaque(value: Any) -> str:
    """A DTCG color object as #RRGGBB: its hex, or its components in srgb,
    hsl, oklch or oklab."""
    hx = value.get("hex")
    if isinstance(hx, str):
        return normalize_hex(hx)
    comps = value.get("components")
    space = str(value.get("colorSpace") or "srgb").lower()
    if isinstance(comps, list) and len(comps) >= 3:
        try:
            c = [0.0 if x in (None, "none") else float(x) for x in comps[:3]]
        except (TypeError, ValueError):
            return ""
        try:
            if space == "srgb":
                return _rgb_hex(*(x * 255 for x in c))
            if space == "hsl":
                return _from_hsl(c[0], c[1] / 100.0, c[2] / 100.0)
            if space == "oklch":
                return _oklch_hex(*c)
            if space == "oklab":
                return _oklch_hex(*oklab_to_oklch(*c))
        except (ValueError, ImportError):
            return ""
    return ""


def _segments(path: str) -> List[str]:
    return [s for s in re.split(r"[.\-_/\s]+", path.lower()) if s]


def _read_text(path: Path, limit: int = 2_000_000) -> str:
    try:
        data = path.read_bytes()[:limit]
    except OSError:
        return ""
    return data.decode("utf-8", errors="ignore")


def _parse_frontmatter(text: str) -> Tuple[Dict[str, str], str]:
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}, text
    meta: Dict[str, str] = {}
    for idx, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            return meta, "\n".join(lines[idx + 1:])
        m = re.match(r"^([A-Za-z0-9_]+)\s*:\s*(.*)$", line)
        if m:
            meta[m.group(1)] = m.group(2).strip().strip('"').strip("'")
    return {}, text


# ------------------------------------------------------------------ ownership


def text_digest(text: str) -> str:
    """The sha256 of ``text`` without its digest line."""
    return hashlib.sha256(_DIGEST_LINE_RE.sub("", text).encode("utf-8")).hexdigest()


def stamp_digest(text: str, comment: bool = False, css: bool = False) -> str:
    """``text`` with a digest line added after its opening ``---``: a
    frontmatter key, or a YAML comment when ``comment`` is True (for a
    DESIGN.md, whose frontmatter keys are a fixed standard). With ``css``
    the line goes inside a block comment that opens the stylesheet: the
    first one when the text opens with ``/*`` on a line of its own, else a
    comment of its own."""
    if css:
        bare = text if text.startswith("/*\n") else "/*\n*/\n" + text
        return "/*\n" + "ux-skill-digest: %s\n" % text_digest(bare) + bare[3:]
    digest = text_digest(text)
    line = ("# ux-skill-digest: %s\n" if comment else DIGEST_KEY + ": %s\n") % digest
    if text.startswith("---\n"):
        return "---\n" + line + text[4:]
    return line + text


def is_ux_skill_text(text: str) -> bool:
    """True when ``text`` carries ux-skill's digest and still matches it:
    what ``is_ux_skill_file`` says of a file, for text already read."""
    m = _DIGEST_LINE_RE.search(text)
    return bool(m) and m.group(1) == text_digest(text)


def ownership(path: Any) -> str:
    """Who a file belongs to: ``missing``; ``owned`` (ux-skill wrote it and
    it is unchanged); ``edited`` (ux-skill wrote it, then a person changed
    it); ``legacy`` (the exact shape ux-skill wrote before the digest
    existed); ``foreign`` (anything else, such as a hand-written file)."""
    p = Path(path)
    if not p.is_file():
        return "missing"
    text = _read_text(p)
    m = _DIGEST_LINE_RE.search(text)
    if m:
        return "owned" if m.group(1) == text_digest(text) else "edited"
    meta, body = _parse_frontmatter(text)
    first = next((ln for ln in body.splitlines() if ln.strip()), "").strip()
    if set(meta) in _LEGACY_KEY_SETS and (first == _LEGACY_MASTER_HEADING
                                         or first.startswith("# Page \u2014 ")):
        return "legacy"
    if p.suffix.lower() == ".md" and DESIGN_MD_MARKER in text and text.startswith("---"):
        return "legacy"
    return "foreign"


def is_ux_skill_file(path: Any) -> bool:
    """True only while ux-skill's own digest still matches the file: a file
    it wrote and nobody has changed since. Safe to overwrite."""
    return ownership(path) == "owned"


# ------------------------------------------------------------------ DTCG


def _is_token(node: Any) -> bool:
    if not isinstance(node, dict):
        return False
    if "$value" in node:
        return True
    return "value" in node and not isinstance(node.get("value"), dict) and (
        "type" in node or set(node) <= {"value", "type", "description", "comment"})


def flatten_dtcg(doc: Any) -> Dict[str, Dict[str, Any]]:
    """Every token in a DTCG (or Tokens Studio) document as
    ``{dotted.path: {"type": ..., "value": resolved}}``. References such as
    ``{color.blue.500}`` are resolved; a reference that cannot be resolved
    keeps its text."""
    raw: Dict[str, Dict[str, Any]] = {}

    def walk(node: Any, path: List[str], inherited: Optional[str]) -> None:
        if not isinstance(node, dict):
            return
        typ = (node.get("$type") or node.get("type")) if _is_token(node) else node.get("$type")
        typ = typ or inherited
        if _is_token(node):
            value = node.get("$value", node.get("value"))
            raw[".".join(path)] = {"type": typ or "", "value": value}
            return
        for key, child in node.items():
            if key.startswith("$"):
                continue
            walk(child, path + [key], typ)

    walk(doc, [], None)

    def resolve(value: Any, depth: int = 0) -> Any:
        if depth > 24:
            return value
        if isinstance(value, str):
            m = re.fullmatch(r"\{([^{}]+)\}", value.strip())
            if m and m.group(1) in raw:
                return resolve(raw[m.group(1)]["value"], depth + 1)
        return value

    out: Dict[str, Dict[str, Any]] = {}
    for key, tok in raw.items():
        value = resolve(tok["value"])
        typ = tok["type"]
        if not typ and normalize_hex(value):
            typ = "color"
        out[key] = {"type": typ, "value": value}
    return out


def _is_design_token(tok: Dict[str, Any]) -> bool:
    """A color or a dimension: what a design token file holds and an API
    key file does not."""
    typ = str(tok.get("type") or "").lower()
    value = tok.get("value")
    if typ in ("color", "dimension", "fontsize", "spacing", "sizing", "borderradius"):
        return True
    if normalize_hex(value):
        return True
    if isinstance(value, dict) and "unit" in value and "value" in value:
        return True
    return isinstance(value, str) and bool(_DIMENSION_RE.match(value.strip()))


def _primary_candidates(names: Iterable[Tuple[str, str]]) -> List[Tuple[str, str, str]]:
    """Every color a name marks as the primary, best named first, as
    (name, hex, the word that marks it): a name that says primary or brand,
    then one that says accent, action, cta or interactive. A leading fill
    word (bg-brand, color-accent) is allowed; a state, a role other than the
    fill, a ramp step or a translucent color is not."""
    ranked: List[Tuple[Tuple[int, int, int, int], str, str, str]] = []
    for order, (name, hx) in enumerate(names):
        segs = _segments(name)
        if not hx or (hx.startswith("#") and len(hx) > 7) or not segs or segs[-1].isdigit():
            continue
        lead = 0
        while lead < len(segs) - 1 and segs[lead] in _FILL_WORDS:
            lead += 1
        words = set(segs[lead:])
        hits = words & _PRIMARY_WORDS
        tier = 0 if hits else 1
        hits = hits or words & _ACTION_WORDS
        if not hits or words & _NOT_PRIMARY:
            continue
        ranked.append(((tier, -len(hits), len(segs), order), name, hx, min(hits)))
    ranked.sort()
    return [(name, hx, word) for _, name, hx, word in ranked]


def _rank_primary(names: Iterable[Tuple[str, str]]) -> Tuple[str, str]:
    found = _primary_candidates(names)
    return (found[0][0], found[0][1]) if found else ("", "")


def _on_color(name: str, named: Dict[str, str]) -> str:
    """The color a token's own text sits in (on-primary, primary-foreground),
    or ""."""
    stem = "-".join(_segments(name))
    for cand in ("on-" + stem, stem + "-foreground", stem + "-fg", stem + "-on",
                 stem + "-text", "text-on-" + stem, stem + "-contrast"):
        hx = named.get(cand, "")
        if len(hx) == 7:
            return hx
    return ""


def _holds_text(name: str, hx: str, named: Dict[str, str], canvas: str) -> str:
    """"" when a primary candidate can carry a button's text, else why not:
    a near-white tint of the page never can, and a fill needs 4.5:1 against
    its own text color, or against the page when it has none."""
    page = canvas or "#FFFFFF"
    if _contrast(hx, page) < _TINT_CONTRAST and _chroma(hx) < _TINT_CHROMA:
        return "%s (%s) is a tint of the page, a hover or surface fill" % (name, hx)
    on = _on_color(name, named)
    if max(_contrast(hx, on) if on else 0.0, _contrast(hx, page)) < _TEXT_MIN_CONTRAST:
        return ("%s (%s) reaches under 4.5:1 against %s, so it cannot carry a button's text"
                % (name, hx, "its text color %s" % on if on else "the page"))
    return ""


def _choose_primary(cands: List[Tuple[str, str, str]], files: List[Path],
                    named: Dict[str, str], canvas: str
                    ) -> Tuple[Tuple[str, str], str, List[Dict[str, Any]]]:
    """(the chosen (name, hex), why, every candidate with its paint count
    when there are several). A name that says primary or brand wins; an
    action color name (accent, action, cta, interactive) is read only when
    none does. A candidate that cannot carry a button's text never wins.
    Of several at one rank, the one the code paints buttons and links with
    most at rest wins; with no such use, the best name. (("", ""), why, ...)
    when no candidate can carry text."""
    refused = {c[0]: _holds_text(c[0], c[1], named, canvas) for c in cands}
    paints = survey.button_paints([c[0] for c in cands], files) if len(cands) > 1 else {}
    listed = [{"token": n, "value": h, "paints": paints[n]} for n, h, _ in cands] \
        if len(cands) > 1 else []
    left = ["%s was left out: %s" % (n, refused[n]) for n, _, _ in cands if refused[n]]
    tail = ("; " + "; ".join(left)) if left else ""
    for tier_words in (_PRIMARY_WORDS, _ACTION_WORDS):
        group = [c for c in cands if c[2] in tier_words]
        ok = [c for c in group if not refused[c[0]]]
        if not ok:
            continue
        name, hx, word = ok[0]
        how = ("its name says %s" % word if word in _PRIMARY_WORDS
               else "its name says %s, an action color, and no color is named primary or "
                    "brand" % word)
        if len(cands) == 1:
            return (name, hx), "%s is the only primary candidate; %s." % (name, how), listed
        if len(ok) > 1:
            best = max(ok, key=lambda c: paints[c[0]])
            if paints[best[0]]:
                n = paints[best[0]]
                others = ", ".join("%s (%d)" % (c[0], paints[c[0]]) for c in ok
                                   if c[0] != best[0])
                return (best[0], best[1]), (
                    "%s is the color the code paints buttons and links with at rest: %d use%s in "
                    "button and link styles and markup, over %s%s." % (
                        best[0], n, "" if n == 1 else "s", others, tail)), listed
            return (name, hx), (
                "%s was chosen because %s; the code paints no button or link with it or with %s "
                "at rest, so confirm it is the action color%s." % (
                    name, how, ", ".join(c[0] for c in ok[1:]), tail)), listed
        rest = [c[0] for c in cands if c[0] != name and not refused[c[0]]]
        over = ("; a name that says primary or brand wins over %s" % ", ".join(rest)
                if rest and word in _PRIMARY_WORDS else "")
        return (name, hx), "%s was chosen because %s%s%s." % (name, how, over, tail), listed
    return ("", ""), ("no primary candidate can carry a button's text: %s; name the action color "
                      "primary, or pass it as the brand primary by hand."
                      % "; ".join(refused[c[0]] for c in cands)), listed


def _luminance(hx: str) -> float:
    def ch(c: int) -> float:
        c = c / 255.0
        return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4
    r, g, b = (int(hx[i:i + 2], 16) for i in (1, 3, 5))
    return 0.2126 * ch(r) + 0.7152 * ch(g) + 0.0722 * ch(b)


def _contrast(a: str, b: str) -> float:
    la, lb = sorted((_luminance(a), _luminance(b)), reverse=True)
    return (la + 0.05) / (lb + 0.05)


def _chroma(hx: str) -> float:
    r, g, b = (int(hx[i:i + 2], 16) for i in (1, 3, 5))
    hi, lo = max(r, g, b), min(r, g, b)
    return 0.0 if hi == 0 else (hi - lo) / hi


def _rank_text(names: Iterable[Tuple[str, str]], canvas: str = "") -> Tuple[str, str]:
    """The page's text color, read by role name. A text word followed by a
    base word (``text.default``, ``text.primary``, ``fg.base``) ranks first,
    then a name ending in a text word, then any other text name. Status and
    promotion groups (offer, sale, danger, ...) never qualify, and a
    candidate must be near-neutral and reach 4.5:1 on white or the canvas."""
    best: Optional[Tuple[Tuple[int, int, int], str, str]] = None
    grounds = ["#FFFFFF"] + ([canvas] if canvas else [])
    for order, (name, hx) in enumerate(names):
        segs = _segments(name)
        if not hx or len(hx) > 7 or not segs or segs[-1].isdigit():
            continue
        words = set(segs)
        if not words & _TEXT_WORDS or words & _NOT_TEXT:
            continue
        if _chroma(hx) > _TEXT_MAX_CHROMA or max(_contrast(hx, g) for g in grounds) < _TEXT_MIN_CONTRAST:
            continue
        paired = any(a in _TEXT_WORDS and b in _TEXT_BEST for a, b in zip(segs, segs[1:]))
        tier = 0 if paired else (1 if segs[-1] in _TEXT_WORDS else 2)
        score = (tier, len(segs), order)
        if best is None or score < best[0]:
            best = (score, name, hx)
    return (best[1], best[2]) if best else ("", "")


def _canvas(names: Iterable[Tuple[str, str]]) -> str:
    for name, hx in names:
        segs = _segments(name)
        if segs and segs[-1] in ("canvas", "page", "background") and len(hx) == 7:
            return hx
    return ""


def _first_family(value: Any, props: Optional[Dict[str, str]] = None) -> str:
    """The face a font list opens with. A var() member is followed through
    ``props`` or passed over for the named families after it; a list that
    opens with a platform keyword (-apple-system, system-ui) is the
    platform's own face, system-ui."""
    if isinstance(value, list):
        value = ", ".join(str(v) for v in value)
    if not isinstance(value, str):
        return ""
    from engine.io.values_in import split_top  # engine.io imports this package
    for part in (p.strip() for p in split_top(value, ",")):
        if not part:
            continue
        if part.startswith("var("):
            face = _first_family(resolve_css_var(part, props), None) if props else ""
            if face:
                return face
            continue
        name = part.strip('"').strip("'")
        return "system-ui" if name.lower() in _PLATFORM_FAMILIES else name
    return ""


def _fonts_from(names: Iterable[Tuple[str, str]]) -> Dict[str, str]:
    """{display, body} from font tokens by name, and data: a face whose
    name says it sets data, figures or code (mono, numeric, tabular), kept
    as a face of its own and never taken for the body."""
    display = body = data = ""
    for name, family in names:
        if not family:
            continue
        words = set(_segments(name))
        if words & survey.DATA_WORDS:
            data = data or family
        elif not display and words & _DISPLAY_WORDS:
            display = family
        elif not body and (words & _BODY_WORDS or not words & _DISPLAY_WORDS):
            body = family
    if not (display or body):
        display = body = data
    fonts: Dict[str, str] = {}
    if display or body:
        fonts = {"display": display or body, "body": body or display}
    if data and data != fonts.get("body"):
        fonts["data"] = data
    return fonts


# ------------------------------------------------------------------ CSS


def css_custom_properties(text: str) -> Dict[str, str]:
    """Every ``--name: value`` declaration in CSS text, first one wins."""
    text = re.sub(r"/\*.*?\*/", "", text or "", flags=re.S)
    props: Dict[str, str] = {}
    for m in _CUSTOM_PROP_RE.finditer(text):
        props.setdefault(m.group(1), m.group(2).strip())
    return props


def resolve_css_var(value: str, props: Dict[str, str], depth: int = 0) -> str:
    """Follow ``var(--x)`` chains to the final value (fallbacks honored)."""
    if depth > 24 or not isinstance(value, str):
        return value or ""
    # One reader of a var() reference: the importers' css_alias.
    from engine.io.values_in import NotRead, css_alias  # engine.io imports this package
    try:
        ref = css_alias(value)
    except NotRead:
        ref = None
    if ref is None:
        return value.strip()
    name, fallback = "--" + ref[0], ref[1]
    if name in props:
        return resolve_css_var(props[name], props, depth + 1)
    return resolve_css_var(fallback, props, depth + 1) if fallback else ""


# ------------------------------------------------------------------ walk


def _walk(base: Path, depth: int, seen: set, out: List[Path],
          keep: Optional[Any] = None) -> None:
    """Files under ``base``, sorted, to the depth and count caps; with
    ``keep``, only the files it accepts, and only they count to the cap."""
    if depth > _MAX_DEPTH or len(out) >= _MAX_FILES:
        return
    try:
        entries = sorted(base.iterdir())
    except OSError:
        return
    for entry in entries:
        if entry.name in _SKIP_DIRS or entry.is_symlink():
            continue
        if entry.is_dir():
            _walk(entry, depth + 1, seen, out, keep)
        elif entry.is_file() and (keep is None or keep(entry)):
            key = str(entry.resolve())
            if key not in seen:
                seen.add(key)
                out.append(entry)


def _token_doc(path: Path) -> Optional[Any]:
    """The JSON document when it is a design token file: it flattens to at
    least one color or dimension token."""
    text = _read_text(path)
    if '"$value"' not in text and '"value"' not in text:
        return None
    try:
        doc = json.loads(text)
    except ValueError:
        return None
    if not isinstance(doc, dict):
        return None
    return doc if any(_is_design_token(t) for t in flatten_dtcg(doc).values()) else None


def _is_built(path: Path, base: Path) -> bool:
    """Generated output: under a build/dist/out folder, or headed
    "Generated ... Do not edit"."""
    parts = {p.lower() for p in path.relative_to(base).parts[:-1]}
    if parts & _BUILT_DIRS:
        return True
    return bool(_GENERATED_RE.search(_read_text(path, 600)))


def _script_sources(script: Path, base: Path) -> List[Path]:
    """The .json files a build script names that exist inside the project,
    resolved against the script's folder."""
    out: List[Path] = []
    for ref in _SCRIPT_JSON_RE.findall(_read_text(script, 200_000)):
        if re.match(r"^[a-z][a-z0-9+.-]*://", ref, re.I) or "package.json" in ref:
            continue
        cand = (script.parent / ref)
        try:
            cand = cand.resolve()
            cand.relative_to(base.resolve())
        except (OSError, ValueError):
            continue
        if cand.is_file() and cand not in out:
            out.append(cand)
    return out


def _package_token_scripts(root: Path) -> List[str]:
    pkg = root / "package.json"
    if not pkg.is_file():
        return []
    try:
        scripts = (json.loads(_read_text(pkg)) or {}).get("scripts") or {}
    except (ValueError, AttributeError):
        return []
    if not isinstance(scripts, dict):
        return []
    return sorted(k for k, v in scripts.items()
                  if _TOKEN_SCRIPT_KEY_RE.search(k)
                  or "style-dictionary" in str(v) or "token-transformer" in str(v))


def _read_colors(docs: List[Any]) -> Tuple[List[Tuple[str, str]], List[Tuple[str, str]],
                                           List[Tuple[str, str]]]:
    """(colors read as hex, font families, color values that could not be read)."""
    colors: List[Tuple[str, str]] = []
    fonts: List[Tuple[str, str]] = []
    raw: List[Tuple[str, str]] = []
    for doc in docs:
        for name, tok in flatten_dtcg(doc).items():
            typ = str(tok.get("type") or "").lower()
            if typ == "color" or (not typ and normalize_hex(tok["value"])):
                hx = normalize_color(tok["value"])
                if hx:
                    colors.append((name, hx))
                elif isinstance(tok["value"], str):
                    raw.append((name, tok["value"].strip()))
            elif typ in ("fontfamily", "font-family") or "family" in _segments(name):
                fonts.append((name, _first_family(tok["value"])))
    return colors, fonts, raw


def detect_existing_system(root: Any = ".") -> Dict[str, Any]:
    """Find an existing design system under ``root`` and read what it declares.

    Returns ``{"found", "root", "sources", "hints", "declared"}``.

    ``sources`` lists each file or folder of the system as ``{"kind", "path"}``
    (path relative to ``root``), the token source first. Kinds:
    ``tokens-source`` (a token file a build script reads), ``tokens`` (a DTCG
    or tokens JSON file), ``css-foundation``, ``built-output`` (generated
    files under build/, dist/ or out/, or headed "Generated ... Do not
    edit"; never edit these), ``master-md``, ``design-md``, ``build-script``
    and ``system-folder``.

    ``found`` is true only on a strong signal: a token file holding at least
    one color or dimension, a foundation CSS file, or a hand-written MASTER.md
    or DESIGN.md. A file ux-skill wrote and a person then edited is not a
    system: commands write beside it instead of over it. A folder, a build script or a
    package script alone is reported under ``hints`` and is not a system.

    Beyond the conventional folders, a token file is also found by what it
    holds, anywhere in the same bounded walk outside docs, examples and
    tests (the walk counts only stylesheets, pages, templates and JSON and
    locale files toward its cap): a stylesheet (.css, .scss or .pcss) whose
    rules are mostly custom properties on the root or a theme selector (or a
    main stylesheet, such as app.css or globals.css, with a theme block of
    its own), and a DTCG file under any name. A theme selector is the root,
    or a class or attribute that names a theme (.dark, .theme-x,
    data-theme, data-mode); a widget's own class (.dp { --dp-bg }) is a
    component, so a widget stylesheet alone is never a system. Built output
    found that way is left out.

    ``declared`` is read from the token source first, then other token
    files, then built output, then foundation CSS: ``primary`` and
    ``primary_token`` (or ``primary_raw`` and ``primary_note`` when the value
    cannot be read), ``text`` and ``text_token``, ``fonts`` ({display,
    body}, plus ``data`` for a face kept for figures, tables or code, with
    ``data_font_from`` when the code, not a token name, says so), ``colors``
    (every named, non-ramp color in the client's naming, a translucent one
    as #RRGGBBAA), ``languages`` (from the project's pages and templates:
    HTML, Blade, JSX and TSX, Vue, Svelte, Astro, ERB and Twig, by their
    html lang and by Arabic script in their text, most used first, then
    the languages only locale files such as messages/ar.json hold) and
    ``direction`` (rtl when <html> or <body> sets dir="rtl", when a page
    whose text is Arabic does anywhere, or when dir is set from the locale
    and Arabic is one of the languages; a language switcher's dir is not).

    The primary is a color whose name says primary or brand; a name that
    says accent, action, cta or interactive is read only when none does (a
    leading fill word, as in bg-brand, is allowed). A candidate that cannot
    carry a button's text (a near-white tint of the page, or under 4.5:1
    against its own text color and the page) never wins. Of several at one
    rank, the one the code fills buttons and links with most at rest wins:
    hover and focus paints are not counted, and class strings in cva, clsx
    and cn calls are. ``primary_candidates`` lists each with its count and
    ``primary_why`` says which was chosen and why; ``primary_note`` says why
    none was, when no candidate can carry text.

    ``disagreements`` lists each token two sources set to different values:
    any two stylesheets that set it on the root or under one theme (an app
    stylesheet that imports the system's file and sets a token again among
    its component rules undoes the system's value), a token file, and a
    hand-written MASTER.md or DESIGN.md palette. Each names the token (and
    its ``theme``), every file with its value, the file that wins in the
    cascade and why: outside a cascade layer beats inside one, :root beats
    html, and then the file loaded last, by its imports (a package name is
    resolved through node_modules or the workspace packages) or a page's
    links. The winner is "" when these files do not decide it, and an
    import that could not be resolved is said to be so.
    """
    base = Path(root).expanduser()
    result: Dict[str, Any] = {"found": False,
                              "root": str(base.resolve()) if base.exists() else str(base),
                              "sources": [], "hints": [], "declared": {}}
    if not base.is_dir():
        return result
    base = base.resolve()

    sources: List[Dict[str, str]] = []

    def add(kind: str, path: Path) -> None:
        rel = path.relative_to(base).as_posix() if path != base else "."
        if any(s["path"] == rel for s in sources):
            return
        sources.append({"kind": kind, "path": rel})

    # Only the root's own files and the conventional system folders are read,
    # so a repository that merely hosts example systems in docs/ is not one.
    system_dirs: List[str] = list(_SYSTEM_DIRS)
    packages = base / "packages"
    if packages.is_dir():
        for child in sorted(packages.iterdir()):
            rel = "packages/" + child.name
            if child.is_dir() and rel not in system_dirs and any(
                    w in child.name.lower() for w in _PACKAGE_WORDS):
                system_dirs.append(rel)
    seen: set = set()
    files: List[Path] = [p for p in sorted(base.iterdir()) if p.is_file()]
    for rel in system_dirs:
        if (base / rel).is_dir():
            _walk(base / rel, 1, seen, files)
    # The whole project, to the same caps, counting only the files the
    # survey reads, so a folder of images never starves a stylesheet.
    html_files: List[Path] = []
    _walk(base, 0, set(), html_files, _surveyed)

    # Token sources: the .json files a token build script reads.
    scripts = [p for p in files
               if (_BUILD_SCRIPT_RE.match(p.name) and "token" in p.relative_to(base).as_posix().lower())
               or _SD_CONFIG_RE.match(p.name)]
    source_docs: List[Any] = []
    # Each hand-written token file with its document, for the disagreements.
    doc_paths: List[Tuple[Path, Any]] = []
    for script in scripts:
        for src in _script_sources(script, base):
            doc = _token_doc(src)
            if doc is not None:
                source_docs.append(doc)
                doc_paths.append((src, doc))
                add("tokens-source", src)

    token_docs: List[Any] = []
    built_docs: List[Any] = []
    css_files: List[Path] = []
    built_css: List[Path] = []
    for path in files:
        name = path.name
        rel_parts = path.relative_to(base).parts
        if any(s["path"] == path.relative_to(base).as_posix() for s in sources):
            continue
        if _TOKEN_FILE_RE.search(name) or (len(rel_parts) > 1 and name.lower().endswith(".json")):
            doc = _token_doc(path)
            if doc is not None:
                if _is_built(path, base):
                    built_docs.append(doc)
                    add("built-output", path)
                else:
                    token_docs.append(doc)
                    doc_paths.append((path, doc))
                    add("tokens", path)
                continue
        if path in scripts:
            add("build-script", path)
            continue
        if name.lower().endswith(".css"):
            parent_words = {p.lower() for p in rel_parts[:-1]}
            if _FOUNDATION_CSS_RE.search(name) or parent_words & {"foundation", "foundations", "tokens"}:
                if len(css_custom_properties(_read_text(path))) >= 3:
                    if _is_built(path, base):
                        built_css.append(path)
                        add("built-output", path)
                    else:
                        css_files.append(path)
                        add("css-foundation", path)

    # Token sources found by what they hold, anywhere in the walk outside
    # docs, examples and tests: an assets/ folder beside the system, the
    # app's own token stylesheets, the theme block of its main stylesheet
    # and a site's globals, and a DTCG file under any name.
    for path in html_files:
        rel = path.relative_to(base).as_posix()
        low = path.name.lower()
        if any(s["path"] == rel for s in sources) or not survey.in_product(path, base) \
                or low.endswith(".min.css") or _is_built(path, base):
            continue
        if survey.is_style(path):
            if survey.css_token_file(path.name, _read_text(path)):
                css_files.append(path)
                add("css-foundation", path)
        elif low.endswith(".json") and low != "package.json" \
                and '"$value"' in _read_text(path, 400_000):
            doc = _token_doc(path)
            if doc is not None and sum(1 for t in flatten_dtcg(doc).values()
                                       if _is_design_token(t)) >= 3:
                token_docs.append(doc)
                doc_paths.append((path, doc))
                add("tokens", path)

    if _package_token_scripts(base):
        add("build-script", base / "package.json")

    for cand in (base / "MASTER.md", base / "design-system" / "MASTER.md",
                 base / ".ux" / "design-system" / "MASTER.md"):
        if ownership(cand) == "foreign":
            add("master-md", cand)
    for cand in (base / "DESIGN.md", base / "design-system" / "DESIGN.md"):
        if ownership(cand) == "foreign":
            add("design-md", cand)

    for rel in system_dirs:
        d = base / rel
        if (rel in ("design-system", "design-tokens", "tokens") or rel.startswith("packages/")) \
                and d.is_dir() and any(d.iterdir()):
            add("system-folder", d)

    sources.sort(key=lambda s: _KIND_ORDER.get(s["kind"], 9))
    if not any(s["kind"] in _STRONG_KINDS for s in sources):
        result["hints"] = sources
        return result

    # ---- what the system declares: the source first, generated output last
    colors: List[Tuple[str, str]] = []
    font_tokens: List[Tuple[str, str]] = []
    raw_colors: List[Tuple[str, str]] = []
    for tier in (source_docs, token_docs, built_docs):
        if tier:
            colors, font_tokens, raw_colors = _read_colors(tier)
            if colors:
                break

    css_props: Dict[str, str] = {}
    for path in css_files + built_css:
        for k, v in css_custom_properties(_read_text(path)).items():
            css_props.setdefault(k, v)
    css_colors: List[Tuple[str, str]] = []
    css_fonts: List[Tuple[str, str]] = []
    for name, value in css_props.items():
        resolved = resolve_css_var(value, css_props)
        hx = normalize_color(resolved)
        if hx:
            css_colors.append((name.lstrip("-"), hx))
        elif ("font" in name and ("family" in name or "face" in name or name.endswith("font"))) \
                or (_FONT_TOKEN_RE.match(name) and _font_list(resolved)):
            css_fonts.append((name.lstrip("-"), _first_family(resolved, css_props)))

    declared: Dict[str, Any] = {}
    cands = _primary_candidates(colors)
    p_from, pool = "tokens", colors
    if not cands:
        cands = [("--" + n, h, w) for n, h, w in _primary_candidates(css_colors)]
        p_from, pool = "css", css_colors
    if cands:
        named_pool = {"-".join(_segments(n)): h for n, h in pool}
        (p_name, p_hex), why, listed = _choose_primary(cands, html_files, named_pool,
                                                       _canvas(pool))
        if p_hex:
            declared["primary"] = p_hex
            declared["primary_token"] = p_name
            declared["primary_from"] = p_from
            if len(cands) > 1 or cands[0][2] not in _PRIMARY_WORDS:
                declared["primary_why"] = why
        else:
            declared["primary_note"] = why
        if listed:
            declared["primary_candidates"] = listed
    else:
        r_name, r_value = _rank_primary((n, v) for n, v in raw_colors)
        if r_name:
            declared["primary_raw"] = r_value
            declared["primary_token"] = r_name
            declared["primary_note"] = (
                "%s is %s, a color this cannot convert to hex; read it from the system and "
                "pass it as the brand primary by hand." % (r_name, r_value))
    t_name, t_hex = _rank_text(colors, _canvas(colors))
    if not t_hex:
        t_name, t_hex = _rank_text(css_colors, _canvas(css_colors))
        if t_name:
            t_name = "--" + t_name
    if t_hex:
        declared["text"] = t_hex
        declared["text_token"] = t_name
    fonts = _fonts_from(font_tokens) or _fonts_from(css_fonts)
    if "data" not in fonts:
        face, where = survey.data_face(css_files, html_files,
                                       lambda v: _first_family(v, css_props))
        if face and face != fonts.get("body"):
            fonts = {**fonts, "data": face} if fonts else {"display": face, "body": face}
            if fonts.get("body") != face:
                declared["data_font_from"] = where
    if fonts:
        declared["fonts"] = fonts
    named: Dict[str, str] = {}
    for name, hx in (colors or [("--" + n, h) for n, h in css_colors]):
        segs = _segments(name)
        if segs and not segs[-1].isdigit():
            named.setdefault("-".join(segs), hx)
    if named:
        declared["colors"] = named
    langs, rtl = survey.languages(html_files)
    if langs:
        declared["languages"] = langs
    if rtl:
        declared["direction"] = "rtl"
    styles = list(css_files) + [
        p for p in html_files if survey.is_style(p) and p not in css_files
        and survey.in_product(p, base) and not _is_built(p, base)
        and survey.declares(_read_text(p))]
    disagree = survey.disagreements(
        base, styles, doc_paths,
        [base / s["path"] for s in sources if s["kind"] in ("master-md", "design-md")],
        html_files, _reading, flatten_dtcg)
    if disagree:
        declared["disagreements"] = disagree

    result["sources"] = sources
    result["declared"] = declared
    result["found"] = True
    return result


def _surveyed(path: Path) -> bool:
    """A file the survey reads: a stylesheet, a page or template, a JSON
    file (tokens, a package manifest, a locale) or a locale file."""
    return survey.is_style(path) or survey.is_template(path) \
        or path.suffix.lower() == ".json" or bool(survey.locale_of(path))


_FONT_TOKEN_RE = re.compile(r"^--font-(?!size|weight|feature|variation|style|stretch|"
                            r"optical|kerning|smoothing|synthesis)[a-z]", re.I)


def _font_list(value: str) -> bool:
    """True when a value reads as a font list, the var() members it may
    open with left aside."""
    from engine.io.values_in import NotRead, read_value, split_top  # engine.io imports this
    parts = split_top(value, ",")
    while parts and parts[0].strip().startswith("var("):
        parts = parts[1:]
    try:
        return bool(parts) and read_value(", ".join(parts))[0] == "fontFamily"
    except NotRead:
        return False


def _reading(value: str, props: Dict[str, str]) -> str:
    """What a value reads as, for telling two values from two spellings of one."""
    resolved = resolve_css_var(value, props)
    return normalize_color(resolved) or " ".join(resolved.split()).lower()


def mark_suggestions(payload: Dict[str, Any], found: Optional[Dict[str, Any]]) -> Dict[str, Any]:
    """``payload`` (an engine result) marked as suggestions when ``found`` is
    an existing system: ``status: suggestion`` plus the ``existing_system``
    block, so no caller mistakes the engine's picks for the project's own."""
    if not found or not found.get("found"):
        return payload
    return {**payload, "status": "suggestion",
            "existing_system": {"root": found.get("root", ""),
                                "sources": list(found.get("sources") or []),
                                "declared": dict(found.get("declared") or {})}}


def client_files_in(out_dir: Any, files: Any) -> List[str]:
    """Of the files a ux-skill build would write into ``out_dir`` (a mapping
    of name to text, or names), the ones that already exist there with other
    content, when ``out_dir`` holds a client's design system (what
    ``detect_existing_system`` finds). A folder whose tokens.json carries
    ux-skill's own extension key is ux-skill's, and a folder that is not a
    system holds no client files."""
    out = Path(out_dir)
    tokens = out / "tokens.json"
    if tokens.is_file() and "io.github.laith0003.ux-skill" in _read_text(tokens):
        return []
    if not out.is_dir() or not detect_existing_system(out).get("found"):
        return []
    theirs = []
    for name in files:
        path = out / name
        if not path.is_file():
            continue
        if hasattr(files, "keys") and _read_text(path) == files[name]:
            continue
        theirs.append(name)
    return sorted(theirs)
